### ISSUE TITLE
Delay issue

### ISSUE THREAD

**Issue by KsuKsuKsu** [PikaMug/Quests#1016]
Quests version is v3.8.0-b35

Hi! I reported about this bug before and you fixed it. But it isn't working still.

I have simple quest: https://pastebin.com/HKNvp9n8

So, i get a quest and did not any actions but all stages finished at the one moment and mission completed.
http://joxi.ru/L21w3aYUR5Jgnr

**Comment by PikaMug** [comment]
Thanks for the report. I don't see any previous tickets by you about this topic, so I'll be treating this as  a new bug unless I learn otherwise.

It's my understanding that there should be a 10 second delay between the stages of your quest. Since the image you shared doesn't have a delay message, I can't tell whether it's just ignoring the time set, or skipping the delay altogether.

Please set a delay message for each stage and let me know whether the messages appear in chat.

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.

**Comment by KsuKsuKsu** [comment]
I did as you asked, then I completed the first stage and this is what I got https://imgur.com/a/uiHjSaK
