### ISSUE TITLE
GUI Command

### ISSUE THREAD

**Issue by UnitedSlayer** [PikaMug/Quests#1019]
**What does your feature do?** Allows a quest GUI to be opened by commands

**How would people use it?** So on my server I plan to have NPCs that have Shops & Quests. So my intended use would be to allow BossShopPro (or other GUI Plugin to open the custom GUI through a command/task

**Comment by PikaMug** [comment]
The built-in quest selection GUI is only intended to be triggered by interaction with a Citizens NPC. In order to accomplish what you're trying to do, I recommend using the [QuestsGUI](https://www.spigotmc.org/resources/questsgui.71666/) plugin in combination with the _/quests take_ command (make sure to set _click-to-take: true_ in QuestsGUI's config file).
