### ISSUE TITLE
Question about version 1.9.0

### ISSUE THREAD

**Issue by bleihof** [PikaMug/Quests#1020]
I apologize for my English, I had to use a translator.

And yes I know the version has long been out of date xD. But I still have a server where I need the version.

I have a question about an old version of the plugin, when it was on Bukkit.

That's why I thought I would write it privately.

If I want to create a stage in which you can dismantle blocks, I understand. But if I want to enter an ID 5: 1 comes: Invalid entry, input was not a list of numbers.

What do I have to enter that he accepts Metaid. The 5: 1 goes.

According to the plugin.yml it is the version: 1.9.0

Thank you for your help even with such a question about an ancient version.

**Comment by Technodate** [comment]
Old versions are not supported.

Try using "5" instead of 5:1 for your block name.
And type "1" when you set the block durability.
![68747470733a2f2f692e696d6775722e636f6d2f393267764744492e706e67](https://user-images.githubusercontent.com/38226281/71025692-df1e1600-2107-11ea-8f38-4f9db90b37f9.png)

If this is not an option for your version, then it might not've been possible yet at that stage.
It might've also been the case that any block with the id "5" is accepted, no matter the damage value.

Either way; if you're expecting to need more help in the future, I'd heavily recommend you update to the newest version of Quests. Currently it's 3.8.1 I believe.

**Comment by PikaMug** [comment]
Thank you @Technodate for the detailed reply. Using a modern version is required for support here, so I’m closing this ticket, especially since OP did not explain why their “need” is warranted.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
