### ISSUE TITLE
Stage "command run"

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [PikaMug/Quests#1021]
**What does your feature do?**
New stage option, to complete stage after player uses some command. Ex if we want to complete quest after somebody make home (/sethome myhome1) "on-command: sethome"

I noticed on discord that im not the only one, who tries to do something like that. Someone said that i should use Denizen, but Denizen script is run after completion, not as a condition to complete a quest.

**Comment by PikaMug** [comment]
Quests 3.8.3 requires Denizen scripts be run as an Action instead, so while this ticket is partially fulfilled, I'll leave it open pending consideration of a "command run" objective.

**Comment by Kryniowesegryderiusz** [comment]
@PikaMug but Action is after obiectives are met, so how can i make an obiective as action using denizen?

**Comment by PikaMug** [comment]
@Kryniowesegryderiusz Actions can be at the start of an objective, too, as well as triggered by other things (chat messages, player death, et al.).

**Comment by PikaMug** [comment]
Since Quests itself as well as a number of other plugins are capable of running commands on a player's behalf, I've come to the conclusion that this functionality is not substantial enough to warrant an objective. The closest comparison would be to a password objective, but even then players will typically be required to solve a word puzzle or locate the password on a sign in-game. Simply typing in a command as instructed is relatively low-effort.

If this is still of interest to anyone, a user by the name of OMR2K has posted a Custom Objective module to accomplish this under the _showcase_ channel in the official Quests community Discord.
