### ISSUE TITLE
Ability to use /questadmin commands on Offline users.

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1040]
**What does your feature do?**
It would allow for Admins or Console to execute /questadmin commands on offline users.
**How would people use it?**
I'm using Denizen to customize how I want my quests to function or be given/finished, but unfortunately if the user logs out while the Denizen script is running and it executes a command to give them another quest or to finish or anything else you can do with /questadmin the user isn't found and their user Data won't be altered. Thus when they log back in they're unable to continue the Quest/story.

**Comment by PikaMug** [comment]
Thanks for your suggestion. The reason this isn't possible is that looking up offline players by their name is deprecated within the Bukkit API - meaning that it's highly discouraged and likely to be removed alongside a future version of Minecraft. The proper method for lookup is using a player's UUID, which is a string of numbers that identifies a player even if they change their name. [Here](https://mcuuid.net/) is a popular website for getting a player's UUID.

If you can provide a Denizen script that runs the command with a UUID instead, I'll make the commands work with UUIDs. Otherwise, I recommend either running the script when the player logs back in, or having someone develop a Bukkit plugin for you that takes care of this for you. The latter should be relatively easy and you could hire someone to do this [here](https://www.spigotmc.org/forums/hiring-developers.55/). Note that the hiring forum I linked is neither sponsored nor affiliated with Quests.

**Comment by Maitlans** [comment]
Hi PikaMug, thank you so much for the detailed reply, would it be possible via using the "lastKnownName:" the Denizen script already knows what the lastKnownName is while the script is executing since it's basically <player>, here's an example of how I use the QA commands https://pastebin.com/afUT0Fh1 I also use them with nextstage, setstage and finish. If this doesn't work then thank you so much I will explore your suggestions. Keep up the amazing work!

**Comment by Maitlans** [comment]
I did a few tests and you may be able to use "<player.UUID>" to obtain the player's UUID using Denizen.

**Comment by PikaMug** [comment]
Getting lastKnownName (from a player's file in the Quests/data folder) would still require knowing an offline player's UUID, since that's what the file names are based on. We could cycle through _every_ file looking for the name, but that would be equal to or worse than the deprecated method as it could take considerable processing time for large servers.

It looks like <player.UUID> is indeed valid, so I'll reopen this ticket.

**Comment by PikaMug** [comment]
@Maitlans In addition to command syntax not supporting UUID, the underlying code doesn't support it either. I'll be updating one command at a time, so please bear with me.

For _/questadmin give [player] [quest]_, the big issue was that some quest Requirements (specifically inventory items, permissions, and custom requirements) need the player to be online. The only solution I could think of was to just skip checking for those Requirements. In other words, running the _give_ command on an offline player will ignore item, permission and custom Requirements.

Please give the following build a try using <player.UUID> and let me know the results:
https://ci.codemc.io/job/PikaMug/job/Quests/61/

**Comment by Maitlans** [comment]
Hey PikaMug, thank you so much for doing this, everything is working as intended, I logout and when I log back in I have the intended quest. The only issue I noticed was one that isn't even part of this which came from the "GPS-Quests v1.1" I'll leave it here as you may be interested. https://pastebin.com/Bv0BRW8p

**Comment by PikaMug** [comment]
@Maitlans The error you linked should be resolved in this build:
https://ci.codemc.io/job/PikaMug/job/Quests/62/

Still working on other commands.

**Comment by Maitlans** [comment]
What should I be looking for and testing with these new commits, to let you know and give you feedback. Thank you again :)

**Comment by PikaMug** [comment]
I've knocked out the rest of the _/questadmin_ commands, which you try with https://ci.codemc.io/job/PikaMug/job/Quests/63/

Note that the item/permission/custom limitation applies to several other commands as well, including certain Rewards in addition to Requirements. I've only actually tested that _/questadmin quit [player] [quest]_ works, so other ones may run into issues, in which case just create a new issue with the console error. Thanks for your patience!
