### ISSUE TITLE
how to add more than 54 quests

### ISSUE THREAD

**Issue by Stoniasawsome** [PikaMug/Quests#1059]
I have a couple questions hope im allowed to bundle them.

version 3.8.6

I have looked thru the posts on this page and found nothing like these issues. The only thing i found was a few closed issues not really like mine. Im also not sure if they are bugs or faults of mine. So ill just ask questions.

1: This question pertains to the /quests list
when i try to add more than 53 quests, i can no longer do /quests list. When i type that command nothing happens. Is there a way to add more than 53 quests? 

2. I used a test subject to test 12 of my quests, he did so. I set a cooldown to 604800 (1 week). When he logged in the day after completing the 12 quests he had 12 points and no quests complete in /quests stats. So his stats reset. Is there something im missing with the data records?

3. Is it possible to make quests "unredoable" like if i never want them to be able to do the quests again after they've completed it once.

sorry for so many questions theres not a whole lot of documentation about my questions.
and thanks for your time.

**Comment by PikaMug** [comment]
Thanks for your questions. I'll answer them in the order received:

1. It sounds like it may be a limitation of QuestsGUI that I have not yet addressed. Does temporarily removing QuestsGUI resolve the issue?
2. This is intentional. Quests that can be taken more than once will not show in _/quests stats_ once the cooldown has expired. This indicates the player may take the quest again.
3. Yes, that would be a normal quest - just don't set any Planner settings at all. If you need the quest to be available at a certain start-date but not be redoable, just set the end-date to something far in the future like year 2999, and don't set a repeat-cycle or cooldown.

**Comment by PikaMug** [comment]
@Stoniasawsome By the way, I've unblocked you from the Discord. Please note that the Discord is for community help; not for bug reports or developer questions (this is explained in the #welcome channel). Continue to use this Github tracker for bugs with Quests, and the QuestsGUI discussion page for bugs with QuestsGUI. Thanks!

**Comment by Stoniasawsome** [comment]
yes removing the gui plugin allows me to continue to create more quests and see them in /quests list
