### ISSUE TITLE
Suggestion to make conversation system

### ISSUE THREAD

**Issue by MrPingviin** [PikaMug/Quests#1062]
**What does your feature do?**
It would make possible to make conversations between the players and the npcs in the start of / during the mission. Delayed conversation lines, just like in Wynncraft.  It would be the best if you could make a system, with multiple participants. ( For example: 1 quest giver, with 2 more citizen npc participant in the conversation)

**How would people use it?**
A lots of (MMO)RPG server could use it. Because we're making big story line what brings more complex quests. We're missing that conversation system so much. That "Kill 2 zombie" and that tiny quest description part isn't enough.

Off: Sorry if I made some mistake, english isn't my main language. Hope you can make it :)

**Comment by PikaMug** [comment]
Thanks for your suggestion! I've addressed this before and found that it really isn't within the scope of this project to do NPC conversations as they wouldn't affect a quest in any way. That said, I'm aware it's often seen as complimentary since a few other quest plugins do offer this, so I'll look into either integrating with- or writing a bridge resource for- another plugin that offers this functionality. Recommendations are welcome.

**Comment by MrPingviin** [comment]
That's would good too. But the thing is, I don't know any plugin what has good conversation system. There was an with almost perfect one ( https://www.spigotmc.org/resources/betonquest.2117/ ) but it's not supported anymore.

**Comment by PikaMug** [comment]
Closing as this has not received any recommendations over the course of a year and a half and, since Denizen scripts can now be run as Actions, this could technically be done with a script. Other alternatives include https://www.spigotmc.org/resources/commandnpc.40295/ and https://www.spigotmc.org/resources/citizenstext.40107/

**Comment by enterih** [comment]
Maybe with this Plugin it could be done. Maybe you talk with the author for a collaboration.
https://www.spigotmc.org/resources/interactions-create-complex-conversations-with-npcs-1-8-1-16.87762/
https://ajneb97.gitbook.io/interactions/api/api-methods
