### ISSUE TITLE
Ability to change the Empty line for objective placeholder.

### ISSUE THREAD

**Issue by call911nowplz** [PikaMug/Quests#1063]
Hello.
It would be great if we could replace an empty line from a place holder, Like %quests_player_current_objectives_Miner% = Nothing (quest not starter) To something else other than emptiness.

Being able to do so, We can display text to player to what they should do next. This way, It's more newbie friendly for our players.
Thanks!

**Comment by PikaMug** [comment]
Sorry, I'm not sure I understand what you're asking. Are you saying that if the player does not have the Miner quest, they get a blank line in chat?

**Comment by call911nowplz** [comment]
Currently, if you use a %quests_player_current_objectives_Miner% and you don't have the quest Miner starter, It shows nothing. Would be nice if we had a string to display a message instead of nothing at all. 
Like  %quests_player_current_objectives_Miner% or any other quest will display "no active quest!" As long as the quest isn't started

**Comment by PikaMug** [comment]
I see. The extension for PAPI isn't really meant to do that, as the methods being called within Quests don't return such strings (hence why it's blank). The idea is that you, the operator, would check `%player_has_current_quest_Miner%` first, and then if it returns "false" you can either show the player `%quests_player_current_objectives_Miner%` or give them an error like "no active quest!"

In other words, while it's possible to do what you're asking within the extension itself, it's expected that the end user will take care of that part. This is also because - while I understand you only want a string - someone else might want a hyperlink, or to spawn a zombie, etc. Just not within the scope of the extension to cover all those cases.

What I recommend first is using the [PAPI-Javascript](https://api.extendedclip.com/expansions/javascript/) extension. I've never used it personally, but I imagine you would create and call a script something like this:

```
noactivequest_miner:
  expression: '%player_has_current_quest_Miner% == false'
  type: boolean
  true_result: '%quests_player_current_objectives_Miner%'
  false_result: 'No active quest!'
```

If it doesn't work or you need further assistance, visit the PAPI Discord at https://helpch.at/discord

(Also any future issues about the Quests extension should go to https://github.com/PikaMug/PlaceholderExpansion-Quests/issues)
