### ISSUE TITLE
I can't add new quests and I can't edit old quests.

### ISSUE THREAD

**Issue by CurrentRiver** [PikaMug/Quests#1077]
**What is your Quests version / build number (do _not_ say "latest")?** 3.8.6

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I just start my server and find this error. I can't add new quests and I can't edit old quests. I tried to start fresh by deleting all the plugin files and updating everything to the latest version but that didn't seem to work either. I feel like I'm out of things to try. I also updated to the latest Spigot 1.12.2 but that didn't work either.
https://pastebin.com/LzeMZx2B

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/Ec8jM6sG Thank you for having a look at this!

**Comment by PikaMug** [comment]
Thanks for your report. This issue is caused by an invalid material(item) name in the quests.yml file. Specifically, a value of '1' would indicate someone tried to use an old ID instead of an item name.

Have you posted the file in its entirety? I don't immediately see anything out of the ordinary. Considering your file has the old, default Stone Miner quest (which was replaced with Iron Miner a while ago), I'm guessing you've been using the plugin for quite some time.

**Comment by CurrentRiver** [comment]
No problem, I appreciate the help. I have posted the whole file. I've been using this plugin for a couple of years haha Since 1.12 at least.

**Comment by PikaMug** [comment]
I've generated a build which should output additional information along with the error. If you would please give a try, and let me know what appears in the console. Thanks for continuing to use Quests!

https://www.dropbox.com/s/ieuq5i98sgkyun9/Quests-3.8.7-github1077.jar?dl=0

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
