### ISSUE TITLE
Quests not syncing with parties

### ISSUE THREAD

**Issue by evanpurl** [PikaMug/Quests#1086]
Not sure why this isn't working, but quest progress does not sync up with other party members. I submitted the issue on the party plugin just in case as well.

**Comment by PikaMug** [comment]
What are your Quests and Parties version numbers? Do you have a quest to share from quests.yml for testing (post to a site like Pastebin/Hastebin)?

**Comment by evanpurl** [comment]
https://pastebin.com/xib1JmVH

Quests: 3.87-b72
Parties: 2.6.14

**Comment by AlessioDP** [comment]
Did you test a different sharing level? Like 2 or 3?
Maybe there is a problem with delivery sharing + level 1 :)

**Comment by evanpurl** [comment]
I just tried all four just now to double-check and still nothing.

**Comment by evanpurl** [comment]
Oh and I'm having this issue with any kind of quest, not just the delivery ones. Just wanted to make that clear.

**Comment by PikaMug** [comment]
I'm having trouble replicating this. The quest you shared has `require-same-quest: true`. Are you certain the other player(s) have accepted the quest first? They must be on the same stage as well.

**Comment by evanpurl** [comment]
> I'm having trouble replicating this. The quest you shared has `require-same-quest: true`. Are you certain the other player(s) have accepted the quest first? They must be on the same stage as well.

Yes I've made sure that they're all on the same quest and stage, but nothing else happens. Nothing gets shared.

**Comment by SimonKertonegoro** [comment]
We're having issues with Party quests too, it seems quest progress Is only shared when people have freshly joined the party. 

We're using the party plugin as more of an ongoing guild system, when you've been part of a guild for a while, for some reason the multiplayer quests stop working for you.

We have tried all combinations of multiplayer quest settings and config. The only thing that seems to have an effect is joining a new party.

**Comment by PikaMug** [comment]
A list of applicable party members is retrieved by ...

https://github.com/PikaMug/Quests/blob/da24ff2bd0535641db697be4dec6bdb7c7681d97/main/src/main/java/me/blackvein/quests/Quester.java#L3705

... which is called whenever progress is due to be shared.

@AlessioDP Is there any reason a Party might not persist a server restart? Or that Party#getMembers might not return a fully populated list?

**Comment by AlessioDP** [comment]
That is a strange behaviour, the API uses the same approach of the internal Parties system to get a party list.

I would like to see a debug log of Parties when this bug is happening, is it possible? @SimonKertonegoro 

You can find how to enable it here: https://alessiodp.com/docs/parties/howtoreportabug

**Comment by SimonKertonegoro** [comment]
[log.txt](https://github.com/PikaMug/Quests/files/4385760/log.txt)

Okay, thanks for the help! Here is the log file.

We played 3 shared quests. All three times it wasn't synchronizing our kills 100% of the time, we did notice that some kills were shared, but not all of them.

**Comment by SimonKertonegoro** [comment]
Oh and it is Esscay and Masuca who were testing the quests. The other players in the log were just hanging around on the server.

**Comment by AlessioDP** [comment]
The log seems okay, I will add some new debug lines for API users with the next update.

When there is a "Got party" request, "Got player" requests are handled correctly


PS. Maybe changing `Parties#getMembers()` into `Parties#getOnlineMembers(boolean)` changes something?
`getMembers` returns the entire list of members (offline too), can this be a problem with `Quests#getQuester(uuid)`?

**Comment by SimonKertonegoro** [comment]
https://gyazo.com/d9d2ce587d802308229a9796d5ef9a14

Players are showing up twice in guild info, could this be causing problems with quests?

I think this is also causing players to have access to GriefPrevention claims even after they leave the guild.

**Comment by AlessioDP** [comment]
It seems to be a Parties only problem, are you using the latest version? I will investigate on it.

About GP, that is normal. Parties gives to party members the GP permission, there isn't a "temporary" permission so its just permanent.

**Comment by PikaMug** [comment]
Wondering if this may be related to #1172

Please see if latest dev version resolves issue: https://ci.codemc.io/job/PikaMug/job/Quests/

**Comment by PikaMug** [comment]
Closing. Feel free to test if issue still persists in Quests 3.9.3 and request re-open.

**Comment by SauROnmiKE** [comment]
**Requesting to re-open**
Using Quests 3.9.3
I have the same issue on a very annoying occasion. I have some quests that require killing a boss, which may or may not be done in a party. I tried the plugin in a smaller quest, where we have to kill some monsters (zombies, skeletons, spiders). I have noticed that kills can be shared, except from the last one, which means that if we were to kill 20 zombies, 19 one them would be shared and the last one would not. So imagine the frustartion of going through a 10-man boss, only to not get the progress because it's the last thing the stage requires. 

One other test, showed me that if I add an extra objective in the game (like talking to an NPC), along with the boss kill, just makes a vert cheap workaround for now. If players kill the boss, they get the kill, but if one talks to the NPC, then no one goes through the next stage. In other words: players can't go to next stages together, no matter the objective. That's why we could kill the 19 zombies, but only the one who got the last hit on the 20th zombie went through the next stage.

Same thing happens for all quest types. Some more examples:
- Deliver progress is not shared
- Talking to NPCs is not shared (although I am not sure if it would be right to do so)

**Comment by Moomay** [comment]
I get the exception when quest sharing with party. I using quests 3.9.2/Parties 2.6.14
https://pastebin.com/xLeyBgaR my quests.yml
https://pastebin.com/QWmLEiSk exception

**Comment by AlessioDP** [comment]
Firstly, you are not using the latest version of Quests!

Secondly, currently latest version of Parties and Quests are broken and they won't work together, I am currently working on a big update of Parties so we are waiting for that update to come out before release a fix :)
I am not sure about that but if you downgrade (not recommended) Quests to 3.9.1 or maybe a lower one, it should work.
I definitely recommend to wait for the new version of Parties instead of downgrade Quests!

**Comment by PikaMug** [comment]
With the release of Quests 4.0.0-rc.1, I'm confident most issues with Parties integration have been resolved. That said, there is little more I can release officially until the new version of Parties is released some time in the future. Feel free to continue reporting issues with the mentality that there may not be an immediate fix.
