### ISSUE TITLE
Please add these functions!!

### ISSUE THREAD

**Issue by Brack04NC** [PikaMug/Quests#1100]
You can add that a mission to be accomplished requires that the player must walk a quantity of blocks before being accomplished, if possible doing a mission may require the killing of random / neutral / bad mobs in general (for example no 10 zombies or 10 skeletons or 10 cows, 10 in general) and although glass can be placed in the free spaces of the gui, thank you if you meet one of these requests.

**Comment by Brack04NC** [comment]
**If it is also possible** to break the blocks in general, for example: "break 30 logs" no 30 of birch or acacia or oak but 30 logs in general.
**### Thanks in advance!!**

**Comment by PikaMug** [comment]
I think distance walked has already been asked, but I can't find the ticket so I'll keep this open pending otherwise.

As for a "random" mob / block objective, see #803 (and #789)

**Comment by Brack04NC** [comment]
That module already created is for blocks in general, how do I transform it for some types of mobs like bad mobs: zombies, skeletons and good mobs: cows, chickens, pigs and for types of blocks, for example break 30 pieces of wood in general, where can I find a code.
I have already read https://github.com/PikaMug/Quests/issues/789, and I don't know what to do with it and how to transform it, thanks for the help !!

**Comment by PikaMug** [comment]
@Brack04NC Assuming you're able to compile Java, it would be a matter of checking the EntityDeathEvent instead of the BlockBreakEvent. More information on the Quest API is available at https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Custom-Quest-API

If you're not able to work in Java, then I suggest hiring a developer to do this for you, as I do not take requests for custom modules. A good place to start is https://www.spigotmc.org/forums/hiring-developers.55/ (not affiliated).

**Comment by Brack04NC** [comment]
Then how do I turn it into a module, that is this:

package xyz.janedoe;

import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.block.BlockBreakEvent;

import me.blackvein.quests.CustomObjective;
import me.blackvein.quests.Quest;
import me.blackvein.quests.Quests;

public class AnyBreakBlockObjective extends CustomObjective {
private static Quests quests = (Quests) Bukkit.getServer (). getPluginManager (). getPlugin ("Quests");

public AnyBreakBlockObjective () {
setName ("Break Blocks Objective");
setAuthor ("Jane Doe");
setShowCount (true);
addStringPrompt ("Obj Name", "Set a name for the objective", "Break ANY block");
setCountPrompt ("Set the amount of blocks to break");
setDisplay ("% Obj Name%:% count%");
}

@EventHandler (priority = EventPriority.LOW)
public void onBlockBreak (BlockBreakEvent event) {
Player player = event.getPlayer ();
for (Quest q: quests.getQuester (player.getUniqueId ()). getCurrentQuests (). keySet ()) {
incrementObjective (player, this, 1, q);
return;
}
}
}
I copy it in a notepad file ++ then I bring it in jar and I put it in the modules does it work as objective?

**Comment by PikaMug** [comment]
Assuming that code has no errors, you need to compile the code into a jar. Here's a tutorial I found by searching "compile java notepad++": https://www.youtube.com/watch?v=J83DFnEe_Uc however, you'd be better off with a dedicated IDE like IntelliJ or Eclipse.

At this point, this issue is now off-topic. Please direct any questions about basic Java knowledge to sources such as video tutorials and StackOverflow (not affiliated).
