### ISSUE TITLE
Choosing Compass Tracking

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1106]
**What does your feature do?**
Players can choose what quest to track via the compass, right clicking on the compass will shuffle between the quests that the user has and it will say in chat which is the quest that is being targeted.
**How would people use it?**
Right now the compass doesn't track quests that the user wants to do, This will help them decide which one to track.

**Comment by PikaMug** [comment]
Thanks for your suggestion. I've made it so that right-clicking a compass will select the next possible target in alphabetical order by name. Left-clicking will reset the compass to bed or spawn location. The `use-compass` setting in config.yml is no longer used. Instead, the `quests.compass` permission is given to players by default - revoke it as desired.

Available through this dev build: https://ci.codemc.io/job/PikaMug/job/Quests/77/
