### ISSUE TITLE
Quests MASSIVE LAG!!!!

### ISSUE THREAD

**Issue by SladeHazard** [PikaMug/Quests#1114]
Quests 3.8.8-b75

Server Version: 1.12.2 lag from quests idk how to reproduce since the plugin wasn't even being used only players were joining / leaving https://gyazo.com/6c0b042c55381590d7ef5a4de6b78d6b PLS FIX this lag

Quests.yml: https://pastebin.com/WNaST9ka

**Comment by PikaMug** [comment]
This is most likely due to the server environment, as Quests does not perform any excessive operations on player join/quit. It’s impossible to be certain, however, as you haven’t provided any benchmarks or comparisons.

If your server has insufficient memory or the hard disk has low read/write speeds, you could try setting ‘generate-files-on-join: false’ in the _config.yml_ file.
