### ISSUE TITLE
Locations with a tight radius are difficult to reach

### ISSUE THREAD

**Issue by marvinjasper** [PikaMug/Quests#1122]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
While doing a runthrough of a quest, my quest tester reported that despite reaching the preset location, the Reach location objective of the quest did not complete as expected. Examining the quests.yml revealed that while the location was bang-on for the X and Z coordinates, the Y coordinate was lower than it should be e.g. we were standing at Y=63, the actual coordinate was Y=62.

Steps to replicate

- Using the Quest editor, make a quest with a Reach location objective in a stage.
- When you configure the Reach Location objective, the editor will prompt you to click on a block to set a location. Click a block on the ground.
- Set a tight radius for this location, let's say 1. ;)
- Make sure that the required elements like Ask message and finish message are set, and save the quest.
- Now, when you go attempt to complete the Reach Location objective of this quest, notice that the coordinates are that of a block on the ground, so the player can't easily reach this location with the radius of 1, because they would have to be _in the ground_.

A couple of workarounds for this.
1. Set the location yourself in quests.yml.
2. Temporarily put a dirt block on top of the block you want the player to reach, and take the location of the dirt block when the editor prompts you.
3. Use a bigger radius to compensate.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/Vp18PNJr

Note that in this example quest, the locations have been fixed and the radius made bigger.

**Comment by PikaMug** [comment]
Thanks for the report. As you've discovered, the clicked block is used as the center of the radius. While I understand that on solid ground this behavior is not desirable in your use-case, the function is working as intended.

Imagine the reverse of your situation, where a user wants a player to reach a location beneath a torch on the wall. Using the torch as a center-point, the operator sets a radius that can only be entered by standing beneath the torch, so that only the player's head enters the radius. Should Quests instead decide to use the block _above_ the clicked one as a center-point, the operator would be understandably confused when their objective doesn't work.

As you've already noted, workaround 2 or 3 are recommended for your situation. Thank you for using Quests!
