### ISSUE TITLE
Quest player data being overloaded & resetting

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1133]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.8-b75

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
No console errors to post this happens when a player has completed over 110 quests usually (depends on the quests they do) but from what I can tell the issue lies in the player data file reading when it tries to get the list of all the quests the player has completed, and they then start a new quest when it reads, it overloads somehow and it will wipe out the past player data containing the amount of quests the player has done, this might be from a string overload into the chat, because the combined length of the strings when listing the quests might be way to long (Several thousand characters at least).

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
This is when there is a large amount of quests... Not a singular quest and they are completed

**Comment by PikaMug** [comment]
Thanks for the report, and I'm sorry for the inconvenience. Is there any chance you have a backup of that player's data that I could use to replicate this?

My first thought would be your server could have ran out of memory, but there would typically be an OutOfMemoryError to accompany that. When you say "overload into the chat," what would be the scenario where this happens? The _/quests list_ command uses multiple chat messages (and not a single message with line breaks), so that shouldn't be an issue. The same goes even if a page number is specified.

https://github.com/PikaMug/Quests/blob/1090b7dbea9c6371596e691c3c798cad349436aa/main/src/main/java/me/blackvein/quests/listeners/CmdExecutor.java#L749-L758

**Comment by PikaMug** [comment]
Forgive me, you said _completed_ quests. Think I've found the issue.

**Comment by Larskei-dev** [comment]
And what was the issue, and has it been fixed...?

**Comment by PikaMug** [comment]
Issue is detailed in commit linked above. Fix will be available in upcoming release.
