### ISSUE TITLE
Quests doesn't link with Citizens on start

### ISSUE THREAD

**Issue by TheOriginalHawk** [PikaMug/Quests#1134]
**What is your Quests version / build number (do _not_ say "latest")?**
-> I tested it on Quests-3.8.8.jar and Quests-3.8.7.jar | Both throw the same error

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
-> I am unsure on how to replicate it. But when loading Quests doesn't link with Citizens. Could maybe be that Citizens is loaded after (See timestamp in pastebin). It has worked before though when I first got the plugin but stopped working a while after.

-> https://pastebin.com/uR0PqThY

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
-> https://pastebin.com/A2S1KC9z

**Comment by PikaMug** [comment]
@TheOriginalHawk Thanks for the report. It appears Citizens is being loaded after Quests, which usually happens when other dependencies (plugins) compete for what order to load in during startup.

Quests will typically try to re-link with Citizens post-start, but it's obviously failing for you. If I'm not mistaken, you mentioned on Discord that you've set `allow-command-quests-with-npcs: true` in your config? I've pushed a commit which should let Quests try to re-link once you try taking an NPC quest via command.

Give the following dev build a try, and keep an eye on your console for a message to the tune of "Successfully linked Quests with Citizens {version.number}"
https://ci.codemc.io/job/PikaMug/job/Quests/80/

Be advised that a lot has changed in the plugin since last release, so there's a possibility of experiencing other, likely unrelated bugs. Also, QuestsGUI may not work with this build, if installed. **Backing up your /Quests folder first is highly recommended.**
