### ISSUE TITLE
Breaking blocks in WorldGuard region not included in quest progress

### ISSUE THREAD

**Issue by Masterfixer06** [PikaMug/Quests#1147]
Hi there,

This is not a terrible bug, but I thought I'd share it. Plugin version 3.8.8.
When breaking blocks in a WorldGuard region with the 'passtrough' flag set on 'allow', the broken blocks won't be included in the quest, if you require to do so in a quest. 

This bug can be fixed by just setting the WorldGuard 'block-break' to true, but still, it seems to me that this shouldn't be like this. The blocks are getting broken, but they aren't included in quest progress. 

Hope you can fix this!

**Comment by PikaMug** [comment]
Not a bug; WorldGuard still likely cancels the BlockBreakEvent even if 'passthrough' is allowed. I'd imagine that's why the 'block-break' flag exists. And, according to [their documentation](https://worldguard.enginehub.org/en/latest/regions/flags/#flag-listing), you may want to consider using the 'build' flag instead.
