### ISSUE TITLE
Commands are not run in console.

### ISSUE THREAD

**Issue by sibraxlis** [PikaMug/Quests#1151]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.38-b75
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
No console errors. Commands are not being run by the plugin, they are being output to the player. A picture is in the discord.
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/Jp7Sxhi6

**Comment by PikaMug** [comment]
Thanks for the report. Please correct the following:

- Invalid version number
- Missing link to picture (or just upload it)

**Comment by sibraxlis** [comment]
https://imgur.com/a/L3srbey
All images are labelled.

**Comment by Technodate** [comment]
Since a recent update all the commands entered in the commands reward section get output to the player, but are still supposed to be ran by the console.
Did you check for the experience difference before and after?

If you do not want the commands to be output to the player, you can override it with a custom message in this format;
![CmdOrD](https://user-images.githubusercontent.com/38226281/77898907-32157680-727c-11ea-9e39-0e727a30effa.png)

**Comment by sibraxlis** [comment]
They are not applying the bonus to the player as expected.

**Comment by sibraxlis** [comment]
I realized i was not on the latest version of quests. The problem persists in 3.9.0-b84

**Comment by PikaMug** [comment]
As @Technodate noted, just because the player sees the command in the rewards list, doesn't mean it's running it on their behalf. It's still being run by the console, per:

https://github.com/PikaMug/Quests/blob/f5e63030718e35d504d80e002292e43e6864fc26/main/src/main/java/me/blackvein/quests/Quest.java#L486-L496

That said, I have no experience with MMOCore, so it'll take me some time before I can test your quest. In the meantime, I recommend editing your quest to use a different command like /ping, just to make sure it's not something on their end.

**Comment by sibraxlis** [comment]
I'm the player in that log. I've verified that my level is in fact staying at level 2. If there's anything to help I can do please let me know. 

I've added a failsafe item for now in the last part that they can use to manually set their level.

**Comment by sibraxlis** [comment]
It looks like warp survival <player> works.

**Comment by PikaMug** [comment]
@sibraxlis I've just discovered that MMOCore is a premium resource. Unless there's a free version I can use for testing, I'm unwilling to proceed.

However, I've tested your quest with a number of other commands such as _/ping_ and _/warp_ and, as you've said, the latter also works just fine. That would lead me to believe this is an issue with either the way MMOCore handles commands issued from the console, or the way you've formatted the command. Either way, I recommend seeking further help from the developers of MMOCore.
