### ISSUE TITLE
Quests stats

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1157]
**What does your feature do?**
when a player does /quests stats or /questadmin stats (player)
it should only show like 10 completed quests, and then let you select a page because when you get to later stages it is impossible to read anything when a player completes like 100 quests it just goes off the screen, same thing as well for actions editor and quests editor so that we can read the actual quests and actions and not have our chats spammed

**How would people use it?**
Pretty self explanatory

**Comment by PikaMug** [comment]
Due to a mistake, _/quests stats_ would create a new line for each completed quest - this was not intended. The next version of Quests will correct the issue. As for quests/actions/conditions listed under Edit in each editor, it is not permissible to have pages as numbers already correspond to menu options. However, one benefit of using [QuestsGUI](https://www.spigotmc.org/resources/questsgui.71666/) is an optional scoreboard that can flip through names in the background of the GUI.
