### ISSUE TITLE
Quest Generation

### ISSUE THREAD

**Issue by Larskei-dev** [PikaMug/Quests#1176]
**Where else have you looked for answers to this question?**
This is extremely specific so nowhere

**Share your question with as much detail as possible?**
Is there a hard limit to how many quests we can make code wise? We are looking into procedurally generating quests, and that means we could easily pushing past the 50,000 quests mark, meaning our quests config could easily exceed over 800,000 lines of config files, so before I go through the trouble of having this developed, is there a hard limit I need to know about inside of quests? Because over half a million lines is a LOT to fit in a single .yml file.

**Comment by Larskei-dev** [comment]
This also means would it be still possible to do /questadmin reload considering currently it takes about 0.2-0.3 seconds to reload about 200 quests, meaning that at 5,000 quests it would take 17.5 seconds to reload, so my question also includes would it be possible to have this run as a asynchronous task, and to somehow speed it up...? Like a /questadmin reload --new where it would not try to reload the quests that are already loaded, it would only look for new quests that have been added

**Comment by PikaMug** [comment]
There is no limit to my knowledge. However, you will likely see a performance drop because such a large file must be loaded into memory - parsing the file once loaded should not affect it nearly as much. Since Quests uses the Bukkit implementation of FileConfiguration, I'm not certain this can be done asynchronously, but feel free to open an enhancement request if you'd like me to look into it.
