### ISSUE TITLE
Subcommand translation caused Unknown command and NULL.

### ISSUE THREAD

**Issue by HauserGrim** [PikaMug/Quests#1194]
Quests 3.9.2

![Снимок экрана (162)](https://user-images.githubusercontent.com/37507220/79124846-d97ac900-7da5-11ea-8928-4fd799d4db0e.png)
![Снимок экрана (161)](https://user-images.githubusercontent.com/37507220/79124883-e992a880-7da5-11ea-9a5b-d1947fcfb930.png)
Used translation downloaded from crowdin
![Opera Снимок_2020-04-13_164415_crowdin com](https://user-images.githubusercontent.com/37507220/79125089-39716f80-7da6-11ea-83da-2913510bdb22.png)
![Opera Снимок_2020-04-13_163257_crowdin com](https://user-images.githubusercontent.com/37507220/79125098-3bd3c980-7da6-11ea-83c5-0af49ca3af76.png)

**Comment by HauserGrim** [comment]
Okay, I had to restart the server so that the option to translate subcommands worked.
Why is this option not enabled by default if used in language files?

This is the first plugin that translate arguments that I see. It’s not convenient for me to often change the language to write part of the command in my own language. I think many server administrators would agree with that.

**Comment by PikaMug** [comment]
@HauserGrim Thanks for your report. The `translate-subcommands` node is `false` by default because it is somewhat experimental. Ultimately, the goal is to also allow the root commands ("/quests", "/quest" and "/questadmin") to also be translatable, so that the entire plugin may be used without English characters. However, this is currently low-priority.

Regardless of whether subcommands are being translated, the plugin should always accept English in addition to the target language. I'll have to take a closer look and ensure this is the case.
