### ISSUE TITLE
Red mushroom doesn't exist.

### ISSUE THREAD

**Issue by Technodate** [PikaMug/Quests#1204]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.2-b94

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
In my case I made a block break quest for fully grown crops, carrots and potatoes.

https://pastebin.com/fEwmrxYr
^ Only says it doesn't know what a red mushroom is.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/7mcTRk0r

Also, if you're able to find out what makes it not test for durability. You might be able to use that as a start on making it possible to destroy *any* kind of logs, or stone etc. for quests.

**Comment by PikaMug** [comment]
Thanks for your report. I'm updating your issue title as there's no indication that the plugin is not checking for durability (in fact, the "`0`" in `Block not found: RED_MUSHROOM.0` _**is**_ the durability). The latter part of your title is correct - red mushroom doesn't exist in the localization keys (an oversight due to the fact that Brown and Red varieties are both simply called "Mushrooms" in pre-1.13 Minecraft).

**Comment by Technodate** [comment]
What about the block durability issue though.
In case it does test for it, it still doesn't work for the crops, carrots and potatoes

**Comment by PikaMug** [comment]
Use https://ci.codemc.io/job/PikaMug/job/Quests/104/

@Technodate It's a non-issue. Quests automatically assumes a durability of 0 if none is specified in the editor. When looking up the key for a material, if one with durability doesn't exist, Quests will then look for it again without durability.

Because crops/carrots/potatoes use durability to determine the state of their growth on pre-1.13, it wouldn't surprise me that might cause issue. Feel free to open a new ticket for them, including any errors.

**Comment by Technodate** [comment]
I used the build, it still doesn't allow red_mushrooms, nor does it know what red mushrooms are.
And I'll open a new ticket for the crops again.

**Comment by PikaMug** [comment]
Working for me?

![mush](https://user-images.githubusercontent.com/2267126/79544524-24723600-805d-11ea-8435-aeda5a566fc6.png)

**Comment by Technodate** [comment]
Interesting, I'm 1.12 myself.

But the mushroom/target is always displayed in white for me.
Only the action is displayed in green. In this case It'd be "Break".

The only other time it's all green for me is when I use a display override.

**Comment by Technodate** [comment]
Alright, it's working for me as well.

But they both display as: "Mushroom" in white, but whatever ig.

**Comment by DateInJapanese** [comment]
[ERROR] [Quests] Block not found: NETHER_WARTS.0
[ERROR] [Quests] Block not found: NETHER_WARTS.3

I guess this error kind of belongs here as well.
This one's about nether warts though.

**Comment by PikaMug** [comment]
@DateInJapanese https://ci.codemc.io/job/PikaMug/job/Quests/106/

**Comment by DateInJapanese** [comment]
Yes! They now exist.
However With nether warts I now have run into the same issue as the crops in #1213.
The part where non of them count that is.
