### ISSUE TITLE
Add Ability to set delay for stage start and completion messages

### ISSUE THREAD

**Issue by DateInJapanese** [PikaMug/Quests#1238]
**What does your feature do?**
It's the same as the Delay & Delay message feature, but for start and completion messages.
This allows you to set delays for start messages and completion messages of stages.
They shouldn't be required to be entered though.

start message delay: Delay in seconds after player enters the stage before start message is shown.
completion message delay: Delay in seconds after the player completes the stage before message is shown.

Having the message delay option for start and finish messages allows you to space out the messages from the objective completion messages, as well as allows you to space out the 'delay message' message and the start message from the next stage.

While denizen can provide this type of needs, it would be so much easier if quests came with that option. It's way quicker being able to select those delays in quests itself, rather than having to learn how to script using a whole other plugin. It saves a lot of time not just because it would be available from the quest menu, but it also saves a lot of time having to test the quests.

**How would people use it?**
It would allow the quest designer to space out the messages more, making it so the player won't be overwhelmed with long sentences when trying to read the story the quest provides.
Or just information in general, mainly the objective display together with the start messages should be able to be split up. The player should be able to read every bit of information at a good pace.

**Comment by PikaMug** [comment]
Problem is that the start and finish messages indicate just that - when a stage can be started or finished. Introducing a delay might ease the amount of text on-screen, but could potentially break the user experience.

For example, Jane is very proficient at quests. She flies through a 4-stage mining quest in 2 minutes, but the start/finish messages have delays of 3 minutes. Jane starts another quest, but is confused about why she's still getting messages from the other quest she just completed. We could decide to just not send her the messages if the quest/stage is already finished, but then Jane might miss out on important story elements.

I think the proper solution here is to just delay the stages themselves entirely, so that messages aren't shown until the stage is "ready" to get attempted.

**Comment by DateInJapanese** [comment]
If you believe delaying the whole stage would achieve the same thing, then that could work.

And it's true that the aspect could potentially break form the user experience, but everything in the quests plugin, or quests in general could. Depending on how the quests designer works with its tools.
- Block breaking > If too many blocks quests get bland.
- If stages are all the same > quests get bland and boring.
- If quests are too difficult > players get bored.
- Talk to npcs 100+ blocks away from each other 10 times > annoying.
- etc.
And that's why it would be optional, and that's also something the quest designer would have to keep in mind.
With quests you're able to tell a story, and with story telling timing is of great importance. Immersion can depend on it, and jokes themselves often heavily depend on timing as well.
It's all part of the execution, and it's up to the designer to optimise it's potential.

Sure in some cases it could break the user experience depending on the execution.
But in many other places it would greatly enhance it.

I still think it would be a good feature to add, so please reconsider it.
