### ISSUE TITLE
[QUEST EDITOR] Specific Quests Requirements

### ISSUE THREAD

**Issue by SNoided** [PikaMug/Quests#1239]
Add a submenu to the quests requirement we can use a specific quest's stage as a requirement

When in the middle (e.g. stage 3) of a quest 1 you need to do another npc's quest (quest 2) for example. well you wouldn't be able to do that quest before finishing quest 1 stage 2
[avoiding quest rushing

**Comment by PikaMug** [comment]
Thanks for your suggesiton.

The biggest obstacle I can see here is that stages can be added, edited, and deleted as seen fit. So in your example, if I were to delete Stages 2 and 3 of the first quest, it would make the second one impossible to take. Alternatively, if one were to delete Stage 1 of the first quest (meaning Stage 3 becomes Stage 2, and Stage 2 becomes Stage 1), should the second quest become available after Stage 1 (since that was previously the stage we wanted) or after Stage 2 (because that's the number we originally selected)?

Combined with the fact that I'd have to add extensive error checking for such an addition, I don't see cost outweighing the benefit here. I think the proper solution here would be to just split Stage 2 of your first quest into a separate quest entirely, which you could then depend off of.

**Comment by DateInJapanese** [comment]
Would a permission checking stage be possible then?
I was looking for something similar to this request, and it can be achieved with permissions too.

I know it was also possible with just splitting up the quest into multiple quests, but if you were to do that so many messages would pop up in chat that I'd rather not have. Quest starting, finishing, rewards, and if active-the titles too.
It breaks quite a bit from the immersion when a quest would be split up like that and if you want to tell it all in one 'story'.

**Comment by PikaMug** [comment]
@DateInJapanese That's a bit off-topic, but checking whether a player has a specific permission for a quest would be a job for https://github.com/PikaMug/Quests/projects/2

Feel free to create a separate ticket requesting that if you'd like it added to the project.
