### ISSUE TITLE
Quests used as requirements can be deleted

### ISSUE THREAD

**Issue by HauserGrim** [PikaMug/Quests#1242]
**What is your Quests version / build number (do _not_ say "latest")?**
3.9.4 b112
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Set quest requirement in other quest
Remove requirement quest
See error with related quests:
[01:29:53 ERROR]: [Quests] Unable to load custom objectives because quest for default2 was null
[01:29:53 ERROR]: [Quests] Unable to load custom objectives because quest for default3 was null
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for your report, but this is not a bug. Quests is informing you that a referenced quest is missing, in this case because you deleted it. In fact, if you go back several lines in the server log, you'll find a more descriptive error to the tune of `me.blackvein.quests.exceptions.QuestFormatException: Requirement quests has invalid quest name [deleted quest], see quest of
ID default2`

I will downgrade the error you shared to a warning, as I figure that's where the confusion arose.

**Comment by HauserGrim** [comment]
I thought that in this case should show a message. ("You must modify these quests so that they do not use it before deleting it.")
