### ISSUE TITLE
Enchanting objective improvements

### ISSUE THREAD

**Issue by DateInJapanese** [PikaMug/Quests#1247]
**What does your feature do?**
Improves the enchanting objective.
Add an option to allow enchanting via anvil.
Add ability to state the level of the enchantment the enchant should have.
Add ability to select item from hand when stating the item to be enchanted.

**How would people use it?**
The same way as the other options.
It's just that these would be *extra* options for designers so they can be more precise when they want to.

**Comment by PikaMug** [comment]
Combining enchantments would likely be a separate objective, the possibility of which might be restricted in that Anvil mechanics are different pre-1.8, but I'll look into it as well as your other points.

**Comment by PikaMug** [comment]
@DateInJapanese Turns out enchanting with anvils isn't viable, but I've updated the objective to load items same as the other Items objectives. Previously made quests with the objective should still work, but I haven't tested it. If you find time, please backup your _quests.yml_ file and give this build a try:
https://ci.codemc.io/job/PikaMug/job/Quests/154/
