### ISSUE TITLE
Index out of bounds error on player join and movement

### ISSUE THREAD

**Issue by delbertina** [PikaMug/Quests#1291]
**What is your Quests version / build number (do _not_ say "latest")?**
Build # 119
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
When some players join, these errors start up and lead to drastic TPS drops and server crash if the player uses an elytra + fireworks.
[https://pastebin.com/FgtUwXiN](https://pastebin.com/FgtUwXiN)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
See #1191

**Comment by PikaMug** [comment]
This has something to do with the reach-location-radii you've specified for your quest. I've created a fix to stop the errors, but your quest may not function properly. If this ends up being the case, please share the quest as it currently appears in your _quests.yml_ file (instead of linking to an old issue).

Try https://ci.codemc.io/job/PikaMug/job/Quests/120/

**Comment by delbertina** [comment]
The quests haven't changed. Here's the link to one of them from that issue [https://pastebin.com/a7XjcV0S](https://pastebin.com/a7XjcV0S)

Will try build 120 to see if that fixes the issues. : )
