### ISSUE TITLE
[New feature] Support Autosell (Clip plugin)

### ISSUE THREAD

**Issue by maxlehot1234** [PikaMug/Quests#1307]
**What does your feature do?**
It will allow me to hook directly into Autosell to create a block-break quests on my prison server

Autosell (Clip's plugin) https://www.spigotmc.org/resources/autosell.2157/ had a priority over every blocks break since he replace them by air and after that the quest plugin was not able to count block break.
Clip told me that you need to handle the event before autosell plugin.

Is it something you can fix, so I can create block-break quests on my server?

Thanks again

**Comment by PikaMug** [comment]
Thanks for the suggestion. However, I have explored this issue before with Clip when I visited his TestPlugins server, and unfortunately I believe the issue lies with AutoSell.

As you said, AutoSell listens for and handles the BlockBreakEvent on _every_ priorities - even MONITOR. Because of this, I have not found a way to observe it for the purpose of a quest.

The bare-minimum solution would be for AutoSell to stop handling the event on MONITOR (which is only supposed to be used by plugins which do not modify the outcome of the event). For more information on how this works, see https://bukkit.gamepedia.com/Event_API_Reference#Event_Priorities

**Comment by extendedclip** [comment]
AutoSell only listens at the priority specified by the end user in the config.
```YAML
block_listener_priority: HIGH
```

**Comment by PikaMug** [comment]
@extendedclip Ah, that explains a lot. Thank you!

@maxlehot1234 It appears the default for that setting is HIGHEST. Since that's what Quests also uses, try setting it to HIGH as Clip has shown.

If memory serves, Quests also uses HIGHEST because it was envisioned that other plugins may wish to cancel the tracking of break-block quest progress. Since I don't know of any cases where that's come to fruition, I'll consider setting it to MONITOR in a future update.

**Comment by extendedclip** [comment]
I managed to fix  integration by setting your block break listener in Quests to HIGH and allowing AutoSell handle the event at HIGHEST. This allowed Quests to process the event as it normally would and AutoSell to process afterwards since AutoSell does modify the outcome of the event to put the drops in the players inventory or sell them.

**Comment by SladeHazard** [comment]
> I managed to fix compatibility by setting your block break listener in Quests to HIGH and allowing AutoSell handle the event at HIGHEST. This allowed Quests to process the event as it normally would and AutoSell to process afterwards since AutoSell does modify the outcome of the event to put the drops in the players inventory or sell them.

What about the plugin Duels Arena Regen I'm having an issue that players who have autopickup enabled keep breaking blocks in a arena where duel arena regen prevents them but autosell auto breaks the block and puts in players inventory

**Comment by SladeHazard** [comment]
just change autosell block listener to MONITOR it works with all plugins!

**Comment by PikaMug** [comment]
Finally had time to test this myself. Once again, thanks for the correction @extendedclip - Quests will use an event priority of HIGH for the next release.

Temporary solution is to set AutoSell listener to MONITOR as @SladeHazard recommended. Once the next release of Quests is available, remember to set AutoSell back to HIGHEST.
