### ISSUE TITLE
Block Breaking Quest Exploit

### ISSUE THREAD

**Issue by Crafter409** [PikaMug/Quests#1353]
So when you create a quest that requires you to break a certain number of blocks, there isn't any form of check to prevent people from just replacing the block and breaking it again to complete the quest.

**Comment by PikaMug** [comment]
Closing as OP did not follow issue template (missing Quests version, et al.).

Bukkit does not offer a cross-version API for checking whether a block was previously mined by a player. Since it is not within the scope of Quests to track such activity, the best we could do is subtract from the blocks-broken count if the desired block is placed. Feel free to open a new ticket as an Enhancement if you'd like to see this implemented.
