### ISSUE TITLE
No GUI Item Question

### ISSUE THREAD

**Issue by malicomrade** [PikaMug/Quests#1375]
**What does your feature do?**
My feature would change the way quests can be taken from an NPC if they don't have a GUI. My idea is that the text in the chat that asks you if you want to accept the quest is clickable or that a GUI pops up with red and green wool (or terracotta, clay etc.) and you can click yes or no. But, the main thing would be that the chat question is clickable.

**How would people use it?**
People would use it if they don't want the player to read the quest info from the lore of an item, but rather from the chat, it would make the plugin more customizable so players can configure their quests more, I would like to see more options on ask-messages shown in general, like a hologram mode etc.

**Comment by DateInJapanese** [comment]
Afaik the chat text can't be made clickable due to the limits the bukkit chat brings. At least, that's what I remember.
But having a placeholder for the ask-message might be nice.

**Comment by PikaMug** [comment]
@DateInJapanese is correct. Clickable text is a Spigot-only feature, and since Quests currently supports 1.7.10 servers (which are often non-Spigot). As for the Yes/No GUI, that's something I would consider adding to QuestsGUI if asked through its discussion thread.

As for options/placeholders on ask-messages, feel free to open a new ticket specifically for that.
