### ISSUE TITLE
Prioritising Quests & much requested flexible placeholders

### ISSUE THREAD

**Issue by DateInJapanese** [PikaMug/Quests#1399]
**What does your feature do?**
Adds the ability for players and admins to prioritise quests.
Adds the option to set a priority value for quest in the editor, default being 0 (the least).
.           The higher priority quest being replaced in the placeholder.

Adds the command for players;
.            /quests follow [quest to prioritise]
Reason for using 'follow' over 'prioritise' is because it's shorter, very understandable, and easier to remember and type, especially for non natives.
If the <quest> part is left empty, it should be reset, to target the server prioritised quest instead of the player targeted one.

Adds new placeholders for targeting the prioritised quest, either by being able to replace the <quest> part in the placeholders with a word used for **always** targeting the prioritised quest. Or by having exclusive placeholders such as;
.            %quests_player_priority_name%, 
.            %quests_player_priority_objectives% 
etc.

**How would people use it?**
Admins would use it in a way where it's easier to make all the placeholders, as well as other displays; making for a much cleaner and faster setup.
While users themselves can, if granted the permission to, have a way to change those displays to show a quest they want to devote their time to at that moment.

In general it would allow for easier oversight of both setup and overview, and I hope there's no-one who doesn't like that.

==

I do realise it's a big feature request, in multiple areas, but since they kind of depend on each other I decided to put it in 1 ticket.

Extra credits to @CaptainAlienHD for taking the time to discuss this into detail.

**Comment by CaptainAlienHD** [comment]
Quick add-up to the things would be adding a
/questadmin follow <player> <quest> - Which would give options for Admins and Staff member in general to help out players in need instead having to /sudo them.
Also the feature would be useful for productive servers that are working with quests on the fly. Quests that cannot be started by players but only Questadmin give quest command. In example players that walk into NPC. Instead having to talk to it. NPC is like. Hey i have Quest for you and player automatically receive the quest. Having option to admin force priority would be really useful for admins. As they can chance follow placeholders right after they give the "flying quest". Of course if player doesn't want to go into it. He can always /quests follow <quest> his quest he was devoted to follow.

**Comment by PikaMug** [comment]
Thanks for taking the time to write this. As I alluded to on Discord, adding this functionality purely for a few, optional placeholders seems excessive to me. Requests to auto-sort priority alphabetically, randomly, by age, by type, etc. will surely follow for a feature many are unlikely to use, but considering the amount of time it could take to manually reorder priority on every quest, I would feel obliged to comply.

However, recent updates have allowed players to select a target ("priority") quest for their Quest Compass. It has dawned on me that placeholders based on said target could be used in a similar manner, albeit with the player having control over selection by clicking, as opposed to an administrator via command. IIRC compass targets are sorted alphabetically, and because this is assigned by the plugin, I would feel more conformable fielding requests.

Let me know what you think.

**Comment by PikaMug** [comment]
Per further discussion on Discord, my suggestion has been partially implemented as https://github.com/PikaMug/PlaceholderExpansion-Quests/commit/5f2851db6d9e68561a31745156d78a200f6b7131

I write "partially" because the Quest Compass currently only points to objectives of Kill NPC, Interact NPC, Deliver Item, and Reach Location. Once I update Quests to also point to nearest Kill Player, nearest Kill Mob, etc. this ticket will be satisfied. Regardless of whether such update occurs in time, the PAPI extension will be published alongside the next release of Quests.
