### ISSUE TITLE
Problem with delivery quests

### ISSUE THREAD

**Issue by Ayon224** [PikaMug/Quests#1401]
**What is your Quests version / build number (do _not_ say "latest")?**

latest
..
Nah for real 3.9.6 and gui 1.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

I am having an issue where I have a set item that you have to deliver to an NPC, but the NPC says something like, Item (Item) x1 is not a required item for this quest!
The difference is 'display name or lore'.

But the item i used i set it by holding it and pressing 0 for the option in the quest editor,

I can only get the delivery quest to work if I dont set a display name or name, but then the quest message doesn't tell you what to deliver. also the delivery message does not work.

This has only recently started happening, as I have done several deliver quests before this one.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
Quest.yml :https://pastebin.com/jLbmj9tS
Console Error : https://pastebin.com/ShuMUG3V

**Comment by PikaMug** [comment]
Thanks for the report. This is hard to diagnose without hands on the virtual item, but which is it? I see several items with lore in your quests file.

**Comment by Ayon224** [comment]
The quest is called "They Called me Crazy"
If you would like to see it ingame I can send you IP,

**Comment by PikaMug** [comment]
I've tested your quest and completed it without issue. The required End Rods were spawned with the EssentialsX _/i [name]_ command. Perhaps the issue lies with how you're obtaining your End Rods? 

![called](https://user-images.githubusercontent.com/2267126/93172562-181c0300-f6f9-11ea-8266-5fe3723e389e.png)

At this point, my recommendation would be to join the [Community Discord](https://discordapp.com/invite/d56CQ6e) and see if anyone might be able to join your server to help figure out the item discrepancy.
