### ISSUE TITLE
Would Love to have more perms for quest creation!

### ISSUE THREAD

**Issue by P-paj** [PikaMug/Quests#1410]
It would be WONDERFUL ❤️  if quests had more permission nodes - specifically ones that can be used to prevent players from using the plugin to fully OP themselves with command rewards on quests

would love to have my admins (Not ops) and even moderators if the permissions were in depth enough be able to work with the plugin - creating npcs, objectives, whole quests basically just without the "rewards" tab
(so they cant give themselves * perms, dupe items, or any other craziness)

Currently only my ops can make quests on the fly, and there are very few of them compared to admins and mods

**Comment by PikaMug** [comment]
Thanks for the suggestion. Rewards are a crucial part of creating a quest, so while I can understand the desire to limit one's control over them, the proper exercise here is to recruit staff that can be trusted not to abuse their abilities. Actions can also perform much of the "craziness" you described, and while I don't recommend it, requirements and conditions could potentially be used to trap or others control players in an undesirable manner. So again, rather than section off parts of the plugin, it is best to hold your staff accountable for any poor choices.

That said, I recognize that determining whom to hold accountable is not always easy. Quests does not currently log most editor processes, and so I'd be glad to look into that. Additionally, I agree that some things are most likely not considered acceptable on any server - namely granting /op status or the * permission. These are situations I will consider preventing in a future update.

**Comment by P-paj** [comment]
Ah - I am definitely understanding that the reward is an important part of quest creation. I mean you do a quest and get a reward haha.

However I, like thousands of others, am not a "business level" server - I can pay for things like questsGUI, but keeping an a staff team that is willing to help with content creation while also being 1000% trustworthy AND active over many months of time is honestly a HUGE ask...

Currently have only been able to allow 1-2 people access ever (these are people ive had to meet online and build trust over months)



Basically I'm not concerned with staff using quests to grief players, or really honestly to give themselves exploited items, those things can be found and fixed... and are mostly non-issues... and i trust some of them enough for /give perms anyway...

 its just the threat of them having OP perms where they could change ANYTHING without me knowing... i suppose a logging system can help, so its not a terrible idea... - **but honestly if there was just some way to put a permission check on only "permission rewards" and "command rewards" (even together as the same perm, you could throw in the "player command" option from the action editor too) just to prevent people from clicking them - it would increase security a TON.**

Would be happy with logging though too, even if just to ban the people after they wreck things..
thanks for the response @PikaMug ❤️

**Comment by P-paj** [comment]
Also im aware all of this can be avoided by having them run quests on a test server (which would have to be paid for, and would need decent ram just to run the same environment of tons of plugins, even with few players)

Then going over every quest action and reward personally before importing it over, then schematic moving or waiting to build what is required for the quest till it was on the main server - I've considered doing this to help bridge that trust issue with some staff, but the cost and time isnt worth it... especially since they are just gonna work at their own pace (again, volunteer lol) and so 1 quest could take them weeks lol!
