### ISSUE TITLE
Bugged planner == daily quests

### ISSUE THREAD

**Issue by LMRig** [PikaMug/Quests#1414]
Hello,
First: It says at a month "Enter a year..."
Then when you enter 9, it says 8 in the planner.
And when you save it, it shows 22.9., as you wrote it during the edit.
But in config is again -1 like in planner.

And I think because of that daily quests don't work. I set it in planner right and the second day I still can't take any.
I also tried to set month to 10, so to be month 9 in the planner and config but also nothing.
Problems:
https://i.gyazo.com/cec7ff29c1d60af7eeeffc766be58e80.png
https://i.gyazo.com/5fae354389055058108768430deaca09.png

**Comment by PikaMug** [comment]
Thanks for the report. The reason the value appears as 1 less than the user input is because of how Java's utility Calendar works - months start at 0 for January, then 1 for February, 2 for March, and so on. Quests intentionally subtracts 1 from the user's input to compensate for this. I will adjust the editor to avoid confusion, but the config will not be changed to maintain backwards compatibility.
