### ISSUE TITLE
view others quests journal

### ISSUE THREAD

**Issue by elaineandsparky** [PikaMug/Quests#1417]
The ability for staff to see other players quests journal either by doing /quests journal (name of player) or by being able to remove it from their inventory when doin /invsee

at the moment /quests journal (name of player) still brings up my own journal and i can't remove journals from inventories.

( tried doing /quests.journal.others in luckperms with no luck)

We often have people say i wasn't given the reward and this will help staff to see why as normally the player just hasn't done it correctly.

**Comment by PikaMug** [comment]
Thanks for the suggestion. There is currently no such functionality beyond giving players the `quests.admin.drop` permission so that they may drop their journals, but obviously this is not a great solution. Due to how the journal is currently coded, it's more likely I'll resolve this through console logging via https://github.com/PikaMug/Quests/projects/6

**Comment by elaineandsparky** [comment]
I hadn't found that permisson node and actually, that works just fine. Thanks

**Comment by PikaMug** [comment]
@elaineandsparky Glad you were able to work out a solution. If you'd like to try the new logging feature, please try the following dev build. Make sure to set `console-logging: 2` in _config.yml_

https://ci.codemc.io/job/PikaMug/job/Quests/152/
