### ISSUE TITLE
BossBarTimer Action

### ISSUE THREAD

**Issue by RinNiko** [PikaMug/Quests#1429]
**What does your feature do?**
So when people accept a quest with timer action it should show Time Countdown on bossbar it easy for tracking :D and people can create a lot things with it
**How would people use it?**
Maybe a little option on timer action people can turn on and off this feature.

**Comment by PikaMug** [comment]
Thanks for your suggestion. Quests currently supports Minecraft versions as low as 1.7.10 and, unfortunately, Spigot only provides BossBar implementation for 1.9 and above. It is for this reason I must decline. However, I'll look into allowing external integration for Action timers so that another developer might create something for you.
