### ISSUE TITLE
Acquire Items task

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/Quests#1449]
**What does your feature do?**

A new category for the "Items" section called "Acquire/Obtain items", when selected the options 1 - Item and 2 - Amount  will appear, when entered you will have the objective "Acquire Rotten Flesh 0/5" this can be used for mob drops and pretty much any format of giving items there is, it will basically detect what items you have in your inventory and add it to the total count or when you pick one up it'll increase it by 1 count.  You would also be able to add several of this one task for different items within the same stage.

I understand one could potentially make a hacky version of this using "Deliver to NPC" but it wouldn't be the same, the Deliver to NPC would be the second step after finishing the "Acquired" items task depending how users decide to make their quests. Virtually every MMORPG with quests has a quest to acquire a certain type and amount of an item, I think it would be really fitting and beneficiary for this awesome plugin to have.

**How would people use it?**

Create quests that need players to obtain a certain type and amount of an item, they can also naturally hook this up to any plugin they may have that gives items to your inventory and it would work.

___________
Thank you

**Comment by PikaMug** [comment]
Thanks for the suggestion. As an objective, to "acquire" an item is ambiguous. Should this be when the mob drops its items? When the player picks these items up? What if their inventory is full? What if they burn the items and walk away?

In Minecraft, there really is no concept of _permanently_ acquiring an item. Many MMORPGs use bound items which specify whether they can be sold or traded or destroyed. This is not done on most Minecraft servers. Standard items (such as your Rotten Flesh) are used for quests and whether or not the player has "acquired" one is entirely conditional. 

Deliver to NPC is far from a "hacky" alternative and is best used here because the result is permanent. It may also interest you to use the "hold item in main hand" condition of the new [Condition Editor](https://github.com/PikaMug/Quests/wiki/Expert-%E2%80%90-Condition-Editor). It will detect whether the items are in the player's hand and notify them if otherwise.

**Comment by Maitlans** [comment]
Hey, yes it would be when a player picks up the items or said item is detected in their inventory, the whole point is just to have a task counter that goes up as you collect said item from whatever means, its up to the player what they want to do with the items past that point if they throw them away then they can't complete the quest and that's on them, they can go again and recollect the items. Many use cases can be expanded from this one simple concept.
