### ISSUE TITLE
Build 179 different issues and notices

### ISSUE THREAD

**Issue by DeadlykillOfficial** [PikaMug/Quests#1511]
**What is your Quests version / build number (do _not_ say "latest")?**
rc.3 b179

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://pastebin.com/XF46XTbk - Error happening whenever a player tries to speak to Citizens NPC which has quests attached to. I'm aware it could be a simple QuestsGUI issue, but wanted to mention it.

There is also an Massive spam happening because of placeholders past 178 i believe 
"[11:26:39 ERROR]: [FeatherBoard] Error in placeholder: {placeholderapi_quests_player_completed_quest_amount}"

Also the newest event that has been added `QuesterPostUpdateObjectiveEvent` does seems to be working with some exceptions i've noticed. Whenever player has objective Place Stone and for example it has Place 5 stone. Whenever player place them it fires the event 5 times properly as it should. But i noticed if a player Break stone during quest period it decreases the amount of Placed stones and doesn't fire the updateObjectiveEvent.
![image](https://user-images.githubusercontent.com/12415714/102477186-50b2dc00-405c-11eb-890a-75ee10dbad69.png)
And this is the same location but with those 5 stone blocks broken right after the task was completed.
![image](https://user-images.githubusercontent.com/12415714/102477256-69bb8d00-405c-11eb-9b4e-8e6854057d8d.png)

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/FHuFV88M - here is the applicable quests.yml i'm testing on 1.16.3 version of the game.

**Comment by PikaMug** [comment]
I understand these may be related, but please limit issues to 1 per ticket.

The QuestsGUI error can be avoided for now by setting `npc.display.enable: false` in its _config.yml_ file. Fixing this requires a new release of QuestsGUI which won't happen until the next release of Quests.

Same applies to the Placeholder error, but I've updated the repository just now. Simply clone it, import as a Java project, and compile as a Jar: https://github.com/PikaMug/PlaceholderExpansion-Quests

Thanks for trying out the events. The subtraction when destroying blocks is intentional, but I suppose the event should fire when that happens. Will look into this now.
