### ISSUE TITLE
Adding a Quest Requirement

### ISSUE THREAD

**Issue by Attila144** [PikaMug/Quests#1527]
**What is your Quests version / build number (do _not_ say "latest")?**

Quests Version 4.0.0-rc.3-b185

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

So the bug starts off when you already have a quest ready to go, then you want another quest to branch off that so you can do multiple quests, as soon as you add the quest as a requirement, it only loads one quest. The other quests that you just completed is still in the Quests.YML but it will not appear in-game.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

https://pastebin.com/7CNrVJzX

**Comment by DeadlykillOfficial** [comment]
None of the quests in pastebin is being connected to the other in any case? You don't have quest requirement for any of the quests?

**Comment by DeadlykillOfficial** [comment]
You must not be using & or § as color codes manager in messages. Otherwise your quests output error that prevents them from loading. Therefor Quests doesn't load. I've just tested the provided Quests and it works perfectly fine when removing all ColorTags which are counted as "unacceptable code point ''" 
Use <colorName> to represent colors in texts like <red> <blue> <green> <pink> <purple> <gold> etc...

**Comment by DeadlykillOfficial** [comment]
And since you have manually updated `rewards` in quests.yml and not used the ingame Editor. All of your reward items are color bugged and preventing Quests from loading. Here is example how i just added custom item to the Rewards section and it's been registered properly in Quests and it does allow me to load it properly:
![image](https://user-images.githubusercontent.com/12415714/103207458-a7db6b00-48fe-11eb-9a95-eb30730b6a4c.png)
![image](https://user-images.githubusercontent.com/12415714/103207462-ab6ef200-48fe-11eb-8e10-ab9c310ee403.png)

**Comment by Attila144** [comment]
Then how come it works when I don't add them to a Required quest?

How come it used to work in the Quests Versions 3.9.2 on another server that I used to run, which I still have the quests.yml for.

**Comment by DeadlykillOfficial** [comment]
V3 and V4 has massive Syntax changes. You would have to recreate all V3 quests again.

**Comment by PikaMug** [comment]
The bottomline here is that manually editing your _quests.yml_ file for anything besides spelling/grammar errors is not supported. If you want colors in your items, use a plugin that allows you to set this (such as [Itemizer,](https://www.spigotmc.org/resources/itemizer.14733/) not affiliated) and load the item from hand.

Once you have a compliant quests file, feel free to make a new issue if there's still an issue with quest requirements.
