### ISSUE TITLE
[Quests]: mcMMO was detected, but is not enabled! Fix mcMMO to allow linkage.

### ISSUE THREAD

**Issue by sbourdeaud** [PikaMug/Quests#1625]
**Where else have you looked for answers to this question?**
In closed GitHub issue, also searched spigot and ofc google
**Share your question with as much detail as possible?**
Getting this message in the server console when starting:
_[Quests]: mcMMO was detected, but is not enabled! Fix mcMMO to allow linkage._

**Comment by TyBraniff** [comment]
Which McMMO Classic version are you using? Which Quests version are you using? I'm Using McMMO Classic 1.6.3 and Quests 4.0.0 and its linking and enabling just fine. 

Please make note if you're using the McMMO Overhaul (Premium) you need to utilize the Overhaul module instead of the built in McMMO features: https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Modules#mcmmo-overhaul

**Comment by sbourdeaud** [comment]
Quests v4.0.0
McMMO Overhaul (Premium).
I have put the Overhaul module in the Quests module directory.  I also have McMMO Overhaul in the regular plugins directory.

**Comment by sbourdeaud** [comment]
Just so we're clear, that was my setup already. I am still getting that message though. : )

**Comment by PikaMug** [comment]
Thanks for the report.

@sbourdeaud Which version of mcMMO Overhaul are you using?

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
