### ISSUE TITLE
Issue when I put fr-QC for translation on Windows. 

### ISSUE THREAD

**Issue by Patfreeze** [PikaMug/Quests#1656]
**build number:** 4.0.1

**The problem and how to replicate it.**
Issue when I put fr-QC for translation, I'm on Windows.
```console
[14:06:52 ERROR]: [Quests] Failed loading lang files for fr-QC because they were not found. Using default en-US
[14:06:52 INFO]: [Quests] If the plugin has not generated language files, ensure Quests has write permissions
```

**Code I use in my own plugin to bypass this problem (hope will help) :**
`getDataFolder()` <--- give me the /plugins/MY_FOLDER_PLUGIN
`File.separator` <--- change the / or \ depend on plateform.

**CODE EXAMPLE:**
```java
File file = new File( getDataFolder() + File.separator + "Players", "playerMario.yml" );
```

**Comment by PikaMug** [comment]
Currently, fr-QC is not a supported language. You may request it by contacting me on [Crowdin](https://crowdin.com/project/translate-quests).

**Comment by Patfreeze** [comment]
It was just an example. Same for fr-FR, fr-CA or only fr.
```console
[11:27:50 ERROR]: [Quests] Failed loading lang files for fr because they were not found. Using default en-US
```

**Comment by DeadlykillOfficial** [comment]
Read the message below this one you just linked.

**Comment by Patfreeze** [comment]
Well, sure I was doing something wrong.
Based on the doc. at 
https://github.com/PikaMug/Quests/wiki/Casual-%E2%80%90-Translations
I go to  https://support.crowdin.com/api/language-codes/

Based also on https://crowdin.com/project/translate-quests
French is 100% completed. (So what is the language-code?)

fr | French
-------------------------
fr-BE | French, Belgium
fr-CA | French, Canada
fr-LU | French, Luxembourg
fr-QC | French, Quebec
fr-CH | French, Switzerland

**Comment by DeadlykillOfficial** [comment]
language-code is correct but most likely your PC is based on French Windows. Which for any programming reason affects extraction of language files into Quests folder due to lack of permission.
This is why it's prompted that selected language is not found because it cannot be extracted of your Quests.jar file.
Solution to that would be open Quests.jar with a WinRar and manually extract the lang folder of it and put it in plugins/Quests folder then loading the language using respective language code should work without any issues.

**Comment by Patfreeze** [comment]
@DeadlykillOfficial Thx for the help... The easiest way! 🎉 I don't know why I didn't think about that. 😄
