### ISSUE TITLE
Data & API issues

### ISSUE THREAD

**Issue by chriss59** [PikaMug/Quests#1796]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests-4.0.7

**Describe the problem and how to replicate it. Any console errors to post _using a pastebin_?**
When I give a quest to a quester at the PlayerJoinEvent, the quest is given at the first join of the server and deleted a few ticks later.
When joining the server a second time, the player keeps his quest. This happens only with MySQL.
https://pastebin.com/yzFudiBS

If you use YAML, the quests you had with custom objective are simply deleted or the progress is not saved when you rejoin the server.
I have tested this with the example.
https://pikamug.gitbook.io/quests/master/custom-quest-api

**Comment by PikaMug** [comment]
Most likely this is because of Quester data not being loaded in time for the method call. While I can and will look into this, my recommended course of action is to delay the call by a few seconds with a runnable task (which should be virtually unnoticeable by the time the player finishes loading in).

There also should be no need to call `#saveData` unless you plan to reference the file/database data directly.

**Comment by chriss59** [comment]
It works with a larger delay. However, the quests journal is not updated. Only when you rejoin the server or use the updateJournal() method.

**Comment by PikaMug** [comment]
I've moved loading from PlayerJoinEvent to PlayerLoginEvent, which fires first. While this resolves the issue, anyone choosing to catch the login event instead will still need employ a delay.

**Comment by PikaMug** [comment]
The solution for this ticket has been reverted due to #1901 

Going forward a delay is the recommended workaround.
