### ISSUE TITLE
Option to disable 'condition' chat spamming or alter intervals.

### ISSUE THREAD

**Issue by Alv5ro** [PikaMug/Quests#1861]
### What does your feature do?

In config let admins allow/disallow the chat spamming if a condition isn't met for each individual quest.
Alternatively allow admins to set the interval period that spamming happens.

### How would people use it?

Quests aren't the main objective for my server, so being spammed in chat that they're not in the correct world to complete a quest can get players a little frustrated, and essentially quitting the quest.

**Comment by PikaMug** [comment]
I do not consider it in the best interest of the player to disable these messages, as many objective types will not be able to indicate to the player that the condition is not yet fulfilled otherwise. However, I will consider making the interval adjustable within a set range (reverting to default upon invalid length).

**Comment by KoltaiArmy** [comment]
Maybe a good solution would be for this, if the message would only appear, when you are trying to advance with that specific quest.
For eg. if your objective is to reach a region, then only show the condition message, when you reached the reagion, but dont bother the player if he is doing something totally else.
