### ISSUE TITLE
Quests Journal

### ISSUE THREAD

**Issue by AccioAce** [PikaMug/Quests#1946]
### What is your Quests version / build number (do *not* say "latest")?

Quest 4.4.0-b328
Paper: 1.18.2

### Describe the problem and how to replicate it.

It seems like there is still a bug with the quests journal. It only shows one page of the quest progress and not the rest. I believe there should be multiple pages to the quests journal like use too. It does need fixing that I know of for sure. Here a screenshot -> https://gyazo.com/5b802b3cd58c1ab6a279c0c6d6f2cfc9

### Any console errors to share?

```shell
No errors on console
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
Here's the quests.yml -> https://www.toptal.com/developers/hastebin/guzabipuna.yaml
```

**Comment by PikaMug** [comment]
Since characters in Minecraft are different widths, which the client can alter via texture pack, there isn't a reliable way to know whether an objective will end up getting line-wrapped. Using multiple pages could work but some will appear more barren than others given we'd have to limit the number of objectives per page. I think a better solution would be to remove objectives from the page as they're completed, exposing new ones. Alternatively, consider using https://browsit.gitbook.io/questsgui/quest-journal

**Comment by AccioAce** [comment]
> Since characters in Minecraft are different widths, which the client can alter via texture pack, there isn't a reliable way to know whether an objective will end up getting line-wrapped. Using multiple pages could work but some will appear more barren than others given we'd have to limit the number of objectives per page. I think a better solution would be to remove objectives from the page as they're completed, exposing new ones. Alternatively, consider using https://browsit.gitbook.io/questsgui/quest-journal

Hello it seems like "click-to-quit" isn't in conflg.yml file.

**Comment by PikaMug** [comment]
That link is for QuestsGUI, not Quests.
