### ISSUE TITLE
Custom Model Data

### ISSUE THREAD

**Issue by iceyhunx** [PikaMug/Quests#1982]
### Where else have you looked for answers to this question?

Can someone help me

How can I put "CustomModelData" in its menu?
My server version is 1.18.1

### Share your question with as much detail as possible.

Can someone help me

How can I put "CustomModelData" in its menu?
My server version is 1.18.1

**Comment by DeadlykillOfficial** [comment]
CustomModelData is not supported by Quests. Meaning you cannot add it anywhere within Quests environment.
Quests support features that are present on all supported versions. Since CustomModelData is 1.14+
But Quests support 1.8 - 1.19 as of right now, until Quests drop support for 1.8 1.9 1.10 1.11 1.12 and 1.13 respectfully.
This feature will not be added and available.
