### ISSUE TITLE
Crops restarting progress 

### ISSUE THREAD

**Issue by LO383krystianch** [PikaMug/Quests#1995]
### What is your Quests version / build number (do *not* say "latest")?

4.5.2-b355

### Describe the problem and how to replicate it.

1. Block breaking missions: when the crops are not fully grown, they restart the mission status https://www.youtube.com/watch?v=fkmHt2vLyH0

### Any console errors to share?

```shell
1. https://www.youtube.com/watch?v=fkmHt2vLyH0, no errors in console
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
https://pastebin.com/CPA5k4hr
```

**Comment by PikaMug** [comment]
Sorry for the late response. This appears to be happening not because crops are broken before they mature, but because you are re-planting the blocks you just broke. It's an intentional mechanic for break-block objectives to prevent players from just placing and breaking the same block over and over.
