### ISSUE TITLE
Bad translation, "Quest complete" at the end of a mission in Spanish.

### ISSUE THREAD

**Issue by ifDaviwy** [PikaMug/Quests#2003]
### What is your Quests version / build number (do *not* say "latest")?

**4.5.2-b355**

### Describe the problem and how to replicate it.

It is very simple, simply by putting the game in the Spanish language, when you complete a quest the text _"Misión complet**o**"_ appears, and it should be _"Misión complet**a**"_, ending in **'a'**.

I realize that this is a very silly mistake, but it is very annoying to see that misspelled in the middle of the screen at the end of a mission.

And as far as I can see I have no way to change it myself, since it shouldn't depend on any configuration file that I can change
![Captura de pantalla 2022-08-15 191646](https://user-images.githubusercontent.com/87628114/184683545-48dd2fb5-9564-4f78-adf1-d2541bcebd3a.png)
.

### Any console errors to share?

```shell
No
```

**Comment by PikaMug** [comment]
Thanks for the report. Translations are handled through [Crowdin](https://crowdin.com/project/translate-quests). Once you've made an account, the quest complete string may be viewed at: https://crowdin.com/translate/translate-quests/6/en-es#3203

However, the default string for es-ES is currently `questCompleteTitle: **MISIÓN COMPLETA: <quest>**` so that doesn't seem to be standard. Either the string has been modified in your files or you have mistaken this plugin for another.
