### ISSUE TITLE
Potienal Quest Bugs

### ISSUE THREAD

**Issue by AccioAce** [PikaMug/Quests#2138]
### What is your Quests version / build number (do *not* say "latest")?

Quest Version: Quests version 4.8.4-b427
Pufferfish Version: 1.20.1+

### Describe the problem and how to replicate it.

Hello Pika, 

I believe these could be following bugs

- CAN NOT SMELT RAW GOLD OR DEEP SLATE GOLD ORE OR ANY ORE'S OVERALL
- Enchant is broken as nothing CAN BE enchanted (ex: books, golden shovel, etc)
- Cannot tame camel (I assume that goes for all 1.20+ mobs)
- When I updated quests.yml and config then /questsadmin reload (RESET some of players quests progress?) - For this one I'm confused so when I edit the quests in the dev server then save it. I swapped the new edited quests.yml folder and config then /questsadmin reload (some players completed progress reset but some didn't?)
- Found a bug for /questsadmin reload (sometime this ERROR shows up - https://gyazo.com/670b3abe263f6e8c167ca57c6fee3f46 and sometimes it doesn't like I need to reload quests a few times for it to work. But most of the time this error shows up.) 
- I have a specific quest bug - I have set a quest for breaking cherry wood 258 times. BUT when the player breaks the cherry wood up to 128 times, it stops there and doesn't count in the progress again so it doesn't go on to 128+ times. 
- None of the brewing potions progress works as well in general.
- ANOTHER ISSUE - I recommend that for smelt's quest, it should be changed to the ORE's no INGOT's - here is an example: If I set it to have it smelt diamond (on the /quest or /quests journal) it will say "smelt diamond" which can confuse players. AND If I set up a display name for smelting diamonds the progress will be broken as in it won't work with smelting diamond ores. 

**Players will be like You cannot smelt diamonds in Furnaces on Minecraft. The same goes with brewing potions as well it confuses players because on the quest journal, it only mentions "Brew potions" with no specific potion given and lack of details.** I'm sure quests would get completely confusing in those situations. 

### Any console errors to share?

```shell
Nope there is no console errors
```

### If applicable, can you provide an example quest from quests.yml?

```yaml
I don't have it as I swapped it out but during the test processes, those are the possible bugs I have listed on my end.
```

**Comment by PikaMug** [comment]
Typically, I would ask that you limit issues to one per ticket, but it's probably easier if I address this many in one place. My answers in the order you've posted are as follows:

- Need example quest
- Need example quest
- Camels are not tameable (just rideable)
- /questadmin reload is not meant to be used while players are actively taking quests. It should be fine if the changes are minimal (like increasing/decreasing block count) but for anything more you should restart the server.
- I will look into this error
- The max item stack on Bukkit-based servers is 64. You're welcome to change this value in file, but it's not supported. Could be a Pufferfish limitation or maybe 1.20 changed something, not sure. Recommended solution is to use multiple stacks of 64.
- Need example quest
- Thanks for the suggestion, I'll consider making this clearer. As for display name, that's intentional.

As for the "Brew potions" issue, I'll need an example quest or at least a screenshot.

**Comment by PikaMug** [comment]
Closing due to lack of further input.
