### ISSUE TITLE
Request: Multiple-file support for quests loading

### ISSUE THREAD

**Issue by SXRWahrheit** [PikaMug/Quests#324]
As we write more and more quests for my server, it would be nice if we could separate them out into modular files for organizational and development purposes.

Benefits would include the ability to organize sets of quests better, avoid breaking the entire quests file with one minor YAML error from file editing (yes, I know you can use the in-game editor, but we generally prefer to write the code - it feels more tangible and it's harder to miss the forest for the trees), and the ability to distribute pre-written quest lines as individual files that server owners can just drag and drop.

Denizen loads every dscript file in its "scripts" folder, and I can imagine Quests doing something similar. You can even make it an optional addition by loading both the existing quests.yml AND any yml files in the "quests" (or otherwise-named) folder and subfolders. The same could be done for events, and any other features that might eventually get their own yml files.

**Comment by FlyingPikachu** [comment]
Important side note: editing quests.yml is never encouraged.

I can see the benefits of separate files, but doing so could seriously impact load/save times if there are enough files. When I was discussing a similar topic with the Citizens devs a while back, it was for this same reason that they were against it.

Recently, an issue was made requesting SQL support. Would this be a reasonable alternative? Although it’s viability needs to be investigated, it would separate quests into organized rows that can be modified in an editor.

**Comment by SXRWahrheit** [comment]
I know manual editing is never encouraged, and I'm fine proceeding under that caveat. Obviously, this would be an "advanced" or "power user" feature.

I use many files for Denizen, and it loads very quickly. Also remember that this would be opt-in, so anyone wanting to make use of the benefit would be taking the tradeoff.

I don't think SQL would accomplish the same goals, and in fact I'd like to avoid it if possible. I think they wanted SQL for data, rather than Quest entries themselves. Regardless, I only run one server - my focus is on modularity rather than mirroring.

**Comment by SXRWahrheit** [comment]
Here is the Denizen code that handles script loading:

https://github.com/DenizenScript/Denizen-Core/blob/master/src/main/java/net/aufdemrand/denizencore/scripts/ScriptHelper.java#L142

**Comment by FlyingPikachu** [comment]
That code loads every script into memory as a single YamlConfiguration, which is fine so long as there isn't a huge number of scripts. Bear in mind that, while Denizen's code merely checks whether the scripts are null at loading, Quests would need to check whether every value is valid for EACH quest file, otherwise "one minor YAML error" could break the YamlConfiguration in memory just the same. Additionally, this would add more time to loading each quest file than Denizen does scripts, so it's not really a fair comparison.

A better comparison would be Citizens, in which you can customize NPCs in as many ways as Quests. Both plugins use a single file because it is simply the most efficient solution code-wise. The customizability is also what makes SQL a challenge (but not impossible).

**Comment by FlyingPikachu** [comment]
That code loads every script into memory as a single YamlConfiguration, which is fine so long as there isn't a huge number of scripts. Bear in mind that, while Denizen's code merely checks whether the scripts are null at loading, Quests would need to check whether every value is valid for EACH quest file, otherwise "one minor YAML error" could break the YamlConfiguration in memory just the same. This checking would add more time to loading each quest file than Denizen takes for its scripts, so it's not really a fair comparison. A better comparison would be Citizens, in which you can customize NPCs in as many ways as Quests. Both plugins use a single file because it is simply the most efficient solution code-wise. The customizability is also what makes SQL a challenge (but not impossible).

Rant over. Being an opt-in feature would be the only way I'd do this, but given this is a likely to be a future only by those with advanced knowledge of the plugin, I have to place this on low-priority for now.

**Comment by SXRWahrheit** [comment]
It should only be run at startup or on an intentional admin command anyway, so a longer load time shouldn't be a huge issue. Yes, of course it would be opt-in.

**Comment by SXRWahrheit** [comment]
I'm writing more and more quests for handling stuff like unlocking magic spells, and running through one giant file is becoming increasingly more of a chore. It would be really great to have this added!

**Comment by KsuKsuKsu** [comment]
I support it.

Manual editing of the quest is the fastest and most visible option. When we do a lot of quest, we will spend forever if we do it on the server.

**Comment by PikaMug** [comment]
So I've come to realize that the real obstacle here is saving quests. In the aforementioned Denizen example, scripts are loaded into a single YAML in memory during startup. However, when the server shuts down, the memory is ultimately just wiped. Scripts can't be edited in-game, so there's nothing to save.

Quests _can_ be edited in-game, which means the single YAML would need to be broken up back into its original files, and then saved. Since quest files don't contain a record of it's filepath (the original file name and where it was saved), this is impossible. I could add that to the file beforehand or create a separate file/object to remember that, but that introduces a whole other slew of challenges.

If someone ever comes across this and wishes to submit a PR, feel free. However, I'm choosing to close this in favor of focusing on MYSQL support and adding a GUI to the in-game editor.

**Comment by KsuKsuKsu** [comment]
great idea!
