### ISSUE TITLE
Requesting tracking of item usage as well as blocks

### ISSUE THREAD

**Issue by DragaoNimhe** [PikaMug/Quests#612]
**What does your feature do?**
Tracks the use of items for quests, such as bonemeal.
**How would people use it?**
To make quests more robust and in depth.

**Comment by PikaMug** [comment]
Sorry for the long wait in my getting to this ticket.

After looking into this, it doesn't seem like this would be easy to implement. Bukkit doesn't provide a blanket event for _successful_ use of an item. There's the PlayerInteractEvent, but that only tells you when a player right-clicks a block, because Minecraft doesn't send packets to the server for right-clicking Air - so items like Ender Pearls and Arrows wouldn't work. Then there's other special cases like food, for which the button has to be held down, water/lava buckets which would also trigger a Place Block objective, Totems of Undying which trigger automatically, et al.

So unfortunately, although I do like the idea of a Use Item objective, it's just not realistic without a dedicated event from Bukkit.
