### ISSUE TITLE
Clickable messages instead of chat listeners

### ISSUE THREAD

**Issue by Sataniel98** [PikaMug/Quests#618]
Hi there!

**What does your feature do?**
I was wondering what you think about making the messages of quest NPCs clickable instead of making players tediously type "1" or "yes" into the chat.

Basically, the only thing that would need to change is that instead of sending plain texts, a JSON message that makes the player send the respective chat message is sent.

I'm sorry if something like that already exists - if you're fine with it, I could make a PR for this.

Have a nice day,
~Sataniel

**Comment by FlyingPikachu** [comment]
Thanks for your suggestion!

It's my understanding that Bukkit requires use of NMS for this, unlike Bungeecord which has the [Chat Component API](https://www.spigotmc.org/wiki/the-chat-component-api/). Since Quests currently supports server versions back to 1.7.9 without use of ProtocolLib, it would be a bit of a burden to add more NMS code to that already being used for such a small feature. Feel free to correct me if I'm wrong, but it's for this reason that I'm going to decline adding this feature for now.

On a related note, I'm hoping to include a GUI option in the future that would cover Yes/No prompts.

**Comment by Sataniel98** [comment]
The Chat Component API is part of the Spigot API, as far as I know as of 1.8. Only in 1.7.9 and 1.7.10, it does require NMS. It could be realized as an optional feature that is not activatable for 1.7.9-10 and CraftBukkit servers.

**Comment by FlyingPikachu** [comment]
Pending drop of 1.7.X support

**Comment by KsuKsuKsu** [comment]
I want it too so much!
It looks awful now http://joxi.ru/EA44K8XHoObW3A

**Comment by PikaMug** [comment]
So I was pretty confident I could get this working by catching ClickEvent.Action.RUN_COMMAND, but it looks like the Bukkit Conversation API only accepts real, non-programmatic chat as a response. That's probably intentional to avoid abuse, but regardless it means there's no way (that I can see) to satisfy this ticket. Thank you for the great idea, though!
