### ISSUE TITLE
Commands On Quest

### ISSUE THREAD

**Issue by PlinioRasch** [PikaMug/Quests#624]
Hi, I'm having this issue that players can use /home example to speak to the NPC and finish the quest super fast, I managed to block stuff like /fly and disable their fly on a quest, but I can't block their /home example. 

My suggestions is to add something that can block all commands, such as *. And once they do a command, I can add the FAIL event and make them fail it once they use a command, please I beg you.

**Comment by PlinioRasch** [comment]
So I mean to add an option for * on the stage events for commands, please. Or at least a way to block /home example, so anything after /home will make it count and not only /home but /home *.

**Comment by FlyingPikachu** [comment]
Events are meant to take place either instantly or on a timer. Since there's no way to know how long a player will take to complete a quest, a new Event is not the solution.

The only way I could see doing this would be to add an option to disable commands in the Quests Editor, in a similar vein to what is planned for #615. Similarly, I'll be placing this on low priority.

**Comment by PlinioRasch** [comment]
Yes please, add an option to disable commands!

**Comment by PlinioRasch** [comment]
Thanks for responding by the way, I hope you add it. Great plugin you made.

**Comment by PikaMug** [comment]
Use http://ci.ac3-servers.eu/job/Quests/732/

You will want to update your English language file. If you're using a different language, the new strings may not be available yet.

The option is available under "General" in the new Edit Options menu in the /quests editor

Note that players will still be able to use Quests commands during a quest.

**Comment by PlinioRasch** [comment]
Thank you so much! Love you.
