### ISSUE TITLE
Requesting an in-chat notification when quest player cooldowns are over

### ISSUE THREAD

**Issue by DragaoNimhe** [PikaMug/Quests#633]
**What does your feature do?**
As the title states, players would receive a notification in chat when a quest cooldown timer is over. If they are offline, it would be nice if they could receive the notifications once they log back in.
**How would people use it?**
To remind them to re-take available quests even if they are at their base, away from the npcs.

**Comment by DragaoNimhe** [comment]
Upon relogging, if multiple quest cooldowns have reset, the notifications could be formatted as such.
The following quests are available to take again:
- Questname
- Questname

A toggle true/false config option or permission node for this feature would be great as well.

**Comment by FlyingPikachu** [comment]
I'll look into adding the first part of your request soon. However, that part about notifying them after logging back in is unlikely to happen, simply because it'd be a tad silly to create a new persistence setup for a single notification. Maybe if Quests gets more types of notifications in the future. Config option will be considered.

**Comment by PikaMug** [comment]
So I looked into it and this isn't really feasible with how cooldowns currently work. They're not on an actual timer, but rather the plugin just checks whether enough time has passed when a player attempts to take a quest. I feel it's not worth rewriting the code for cooldowns just to satisfy this ticket. Thank you for the suggestion.
