### ISSUE TITLE
New Player Joins, Crashes Server

### ISSUE THREAD

**Issue by FuneralSuits** [PikaMug/Quests#733]
Quests Version: 3.6.4-b697
Paper Spigot Version: 1.13.2-R0.1-SNAPSHOT

Server suddenly crashed after a new player joined, here is console readout from that crash:
https://pastebin.com/jKasT92s

Appears to be a problem with Quests that caused the crash, not sure what any of this information means though as I'm not a code wizard by any means. Thanks & goodluck!

**Comment by PikaMug** [comment]
Would you mind posting this player's data file with Pastebin? Should be at /plugins/Quests/data/3b6e04de-1c61-4902-9dbc-7aacb1d0830c.yml

If you could also tell me what date that file was created, I'd appreciate it. My initial guess is that the player is not actually new and their old data file is so outdated that it could not be properly read by recent versions of Quests.

**Comment by FuneralSuits** [comment]
Here is /plugins/Quests/data/3b6e04de-1c61-4902-9dbc-7aacb1d0830c.yml's file:
https://pastebin.com/ykcdNg6q

The file appears to have been created today. The players ip and username/uuid have never joined the server before. Also here's the crash report:
https://pastebin.com/R6mpMyWk

Thanks for the help Pika, appreciate it

**Comment by PikaMug** [comment]
If the file was created "today", then my guess is wrong. It was a possibility for Quests to still have data on the player if your server's "firstseen" data was ever reset (since Quests doesn't rely on it).

Looking at your crash report, this appears to be an issue with PaperSpigot, despite the fact that the Quests error appeared first. In the report, there's no mention of Quests other than it being installed on the server. If Quests were the cause, it should've been present in the stack trace.

I'll add some checks which should make this more obvious should it happen again, but that said, definitely report this to the PaperSpigot team if it happens a second time.

**Comment by PikaMug** [comment]
Use http://ci.ac3-servers.eu/job/Quests/700/ once available
