### ISSUE TITLE
Error when trying to move player to next stage.

### ISSUE THREAD

**Issue by itaquito** [PikaMug/Quests#736]
**What is your Quests version / build number (do _not_ say "latest")?**
Quests 3.6.3-b668
Paper spigot: Paper version git-Paper-564 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I think its because the quest requieres the player to mine 3 stacks of obsidian, and the plugin gets mess up with that
Also, this error happens when I try to move the player to the next stage.
https://pastebin.com/EBQLRQ3C
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/NraxWrLt

**Comment by PikaMug** [comment]
Using Quests 3.6.4, I was able to use _/questadmin nextstage_ to advance the quest without issue. First, from the console to progress to the second stage, and then from in-game to complete the quest.

![obsid](https://user-images.githubusercontent.com/2267126/54484572-ded2b080-483f-11e9-9b6b-a85528e4e5e1.png)

Please try upgrading to the latest Spigot release (3.6.4) and if the issue persists, post the error generated by that version here and I'll reopen the issue.

**Comment by itaquito** [comment]
Emmm, this happened...
![image](https://user-images.githubusercontent.com/30180886/54484790-6e716280-4832-11e9-9d01-c98da8c2fb98.png)

**Comment by PikaMug** [comment]
@itaquito Interesting. Did you get any form of error?

**Comment by itaquito** [comment]
Nop, Besides that the second stage is also strange
![image](https://user-images.githubusercontent.com/30180886/54484796-a37db500-4832-11e9-89dd-0db2d4a4e741.png)
I only gave the NPC 1 stack of obsidian an aparently that was enough, also the rewards are weird, its supposly to give 3 stacks no 36, 8 and 36 of obsidian. xD

**Comment by PikaMug** [comment]
So, for the Break objective issue you demonstrated in this image:

![itaquito image](https://user-images.githubusercontent.com/30180886/54484790-6e716280-4832-11e9-9d01-c98da8c2fb98.png)

This is because that interface does not expect multiple stacks of the same block type. What you'd actually want to do is change it to a single stack of the amount you want (in this case 3 x 64 = 192). So it'll come out looking like this:

![192](https://user-images.githubusercontent.com/2267126/54484968-eb0e3c00-4846-11e9-9683-62641e4bda57.png)

Still looking into the Deliver objective issues.

**Comment by PikaMug** [comment]
Seems to be a similar car for the Deliver objective - it can only handle one stack of the same block type. However, unlike the Break objective, this interface can't take an amount greater than 64 because of how this type of objective required you physically hand an item over (which Minecraft limits to 64). Because of that, there's no solution to this other than splitting the objective into separate stages (so 64 across 3 stages = 192 total).
