### ISSUE TITLE
New Lines in GUI Start as Purple

### ISSUE THREAD

**Issue by BUTTERLOVER7683** [PikaMug/Quests#740]
**What is your Quests version / build number (do _not_ say "latest")?**

- Quests 3.6.3-b668 (_I think this is it_)

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

- At the beginning of every new line of the lore of the items in the quests GUI, it forces the text to be purple unless otherwise formatted. Pictures for reference: https://i.imgur.com/Cl4uOYE.png | https://i.imgur.com/z79eiFN.png
- Do note how in the first one, all text starting at "awry" turns purple and italicized and in the second, everything is in purple starting at "gather" until it was reformatted starting at "2 pieces."

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

- I suppose? Quest from the second image because it's a better example: https://pastebin.com/kj8CvKSd (_the important part is the ask message_)

An additional message: seems like the main solution to this is just to put the color code again and again at the start of each line, but if I may, perhaps some tweaking that doesn't make that necessary (_if that's even possible_)?

**Comment by PikaMug** [comment]
This has been known since #57 

Dark purple is the default lore color within Minecraft, which the client applies to each new line. Since there's no way for Quests to know where a new line is going to start, it's not possible to just add in color programatically. We can't simply count characters because each letter has a different width and, to make matters even more complicated, Quests supports other languages with _thousands_ of non-English characters which we'd have to account for.

I'll push a commit which fixes the default quest you shared (which probably broke because I changed "Stone Miner" to "Iron Miner" a while ago for compatibility reasons). However, there's nothing I can do about lore due to the aforementioned obstacles. I'll mark this as Help Wanted in case anyone would like to share ideas (although I'd much prefer a Pull Request).

**Comment by PikaMug** [comment]
It seems there is no ideal solution for this. If anyone comes up with a bright idea, Pull Requests are welcome.
