### ISSUE TITLE
PlaceholderAPI placeholders in requirements

### ISSUE THREAD

**Issue by SXRWahrheit** [PikaMug/Quests#742]
**What does your feature do?**

Allows specifying PlaceholderAPI placeholders in requirements for quests

**How would people use it?**

* Specify a placeholder and an expected value (if none listed, defaults to expecting `true`)
* The requirements are only met if the placeholder matches the expected value (or, again, `true` if none is listed).

**Comment by PikaMug** [comment]
I've given this some thought and, if Quests were to support doing requirements this way, it would essentially undermine the Requirements API for modules in favor of using PlaceholderAPI. Although it'd be a great alternative for those unfamiliar with Java, it's in this project's best interest to directly handle custom requirements rather than do so indirectly through PAPI, or any other plugin.

Perhaps a module could be made to facilitate this? https://www.spigotmc.org/forums/hiring-developers.55/

**Comment by Maitlans** [comment]
That's a shame, I think it being available within the plugin itself would do more good than harm as pretty much most people who want to integrate quests with another plugin could do it this way rather than hitting a road block within their creativity.

**Comment by PikaMug** [comment]
@Maitlans The version released _yesterday_ does literally this, but as a Condition rather than a Requirement.
https://www.spigotmc.org/resources/quests.3711/update?update=367966
