### ISSUE TITLE
Currently, Quests does not support crates

### ISSUE THREAD

**Issue by Castiella** [PikaMug/Quests#748]
This is a bug/feature report.

Currently, Quests does not support crates. (crazycrates)

When I try to load a crate key in my hand to give it to the quest rewards via the editior, it registers correctly that it has been loaded, but if i save the quest and try to complete it, i get nada.

So I'm wondering, would you provide support for this?

thanks for the great free plugin.

**Comment by Castiella** [comment]
(I would also be willing to donate to have this feature added, I know its cheeky to ask features for a free plugin!) x

**Comment by SXRWahrheit** [comment]
Please provide the relevant files (quests.yml excerpts, crates configs, version numbers, any relevant server log snippets), etc via pastebin links for review.

**Comment by PikaMug** [comment]
Although OP stated this to be part "bug... report" this is in fact a feature request, which does not require version numbers or excerpts.

@Castiella Thanks for your interest in Quests. The plugin does not support CrazyCrates to any capacity, so it's no surprise that their keys don't work for quests. The functionality you've requested is better left to a [module](https://github.com/PikaMug/Quests/wiki/Master-%E2%80%90-Quests-API) and, as such, is going to be low priority.

Since you're willing to pay, it would be best to find a developer willing to create the module for you at https://www.spigotmc.org/forums/hiring-developers.55/ (service(s) not affiliated with Quests).

**Comment by Castiella** [comment]
As long as I have your permission to do this, I will do this :) thank you!
