### ISSUE TITLE
MoreFish Support

### ISSUE THREAD

**Issue by t0xic1** [PikaMug/Quests#764]
https://www.spigotmc.org/resources/morefish-improved-fishing-and-fishing-competition.22926/

**What does your feature do?**

Currently using the MoreFish plugin doesnt count the fish towards catch fish goal

**Comment by PikaMug** [comment]
After investigation, I'm unable to provide support for MoreFish as it does not appear to have any event system nor an accessible way to check whether a caught fish is a MoreFish fish. Furthermore, the author (@elsiff) appears to be inactive since February (no plugin updates, no Github activity, unresolved pull requests).
