### ISSUE TITLE
Feature Request : Please Add Singleplayer Quests Option in Planner/Requirements

### ISSUE THREAD

**Issue by seanlew98** [PikaMug/Quests#807]
**What does your feature do?**
- Makes a certain quest only available to one player at a time.
(User will have to configure fail timer in quests events to prevent problems perhaps?)
- Reason for the request is I have many quests involving killing npc's, or npc's following player into dungeon, with the follow & unfollow & respawn commands set in the events at the start and end points.
- However, if multiple players take the quest at the same time, it'll all get clashed up cause they're using the same NPC's.
- Shorter timers can also be set to only span over one stage instead of the whole quest, using events to start & stop timers in each stage. But that'll be totally up to the user to set up.

**How would people use it?**
- Enable singleplayer mode either in the Planner/Quest Requirements. And use Fail Timers to prevent players taking quests and not doing the objectives, making other players unable to take them.

Fhankyu sho sho very very much!!

Edit : Actually kinda figured out a way to do it by using events to remove everyone's permission to join specific quest, and adding it back after the player either fails or completes the quest. But will still be great if such a feature is added. Thanks again! :D

**Comment by PikaMug** [comment]
Thanks for your ticket.

Quests aims to provide a reasonable level of customizability to operators while also improving the player experience. While I realize that players competing over an NPC objective is not ideal, blocking others from completing the objective until someone else does first is not a great solution. Players will simply compete over whom is next in line, even if a proper queue system with timers were to be implemented.

What you are trying to do is best accomplished with client-side NPCs, which has been discussed previously on the official Discord. While some plugins like the premium QuestCreator offer this feature, it's made possible via NMS, which you can read about at https://riptutorial.com/bukkit/topic/9576/nms

This project avoids using NMS because, to quote that link, "Use of NMS code is discouraged as it breaks often between Minecraft version changes and cannot be supported by Bukkit or Spigot as they do not create, own, or maintain it." Since I am the only major contributor to Quests and must ensure survivability of the plugin should I no longer be able to maintain it, I feel that  it would be irresponsible of me to further complicate it. However, I do entertain all Pull Requests.

My suggestion would be, rather than enforcing "singleplayer", encourage players to work together using the Parties or DungeonsXL plugins. Using one of these will let players progress stages at the same time. For example, if a player in one group kills an NPC during a quest, all players in that group will advance to the next stage. https://github.com/PikaMug/Quests/wiki/Beginner-%E2%80%90-Dependencies
