### ISSUE TITLE
Duplicate quests upon reload

### ISSUE THREAD

**Issue by Technodate** [PikaMug/Quests#811]
**What is your Quests version / build number (do _not_ say "latest")?**

3.6.8-b747

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**

Steps to replicate;
1 Create any quests and /questsadmin reload
2 Take the quest
3 Edit that quest in game, save and /questsadmin reload 
4 Take the quest again

Then when you check that persons quests using /questsadmin stats player
It shows the quest 2 times.

The problem is; that they are both quests, and the player can complete the quest twice that way.
The bigger problem is that you cannot take away the quest from the player using /questsadmin quit 

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

This can be done with any quest

**Comment by PikaMug** [comment]
Please confirm whether this still occurs on Quests 3.7.0.

**Comment by Technodate** [comment]
It does.

**Comment by PikaMug** [comment]
I was able to replicate this, however editing the quest in step 3 was not necessary. Nothing jumps out at me as to the cause, but I hope to find a solution sooner than later.

**Comment by XDarkflavio** [comment]
i have the same problem, but when i dont know why I cant delete a duplicate.
when it says "enter quest name" nothing happens and i still have all the duplicates in /quests list.

**Comment by PikaMug** [comment]
Since the Jenkins server is down, try this build and let me know the results:
https://www.dropbox.com/s/vlu1dd2v0hxibrh/Quests-3.7.1.jar?dl=0

**Comment by Technodate** [comment]
I'll be sure to try it tomorrow morning, and I'll tell you the results right after I get them.

**Comment by XDarkflavio** [comment]
Since I'm not the owner of the server I will try and ask the owner... As
soon as I get the results I will let you know. Thanks for the build

Il lun 3 giu 2019, 22:43 Technodate <notifications@github.com> ha scritto:

**Comment by Technodate** [comment]
It seemed to be pretty bad.....

As in; I had several quests taken, in later stages, but upon updating it, it cleared my quests taken list

**Comment by Technodate** [comment]
On top of that, the quests are still being duplicated upon questsadmin reload

**Comment by PikaMug** [comment]
@Technodate Could you provide one of the quests which you're able to duplicate on reload? The build seems to have at least fixed the quest I'm testing with.

**Comment by PikaMug** [comment]
My apologies for the inconvenience that build caused you.

It looks like I misjudged the nature of this issue. As it turns out, these duplicate quests are by design. When a quest is edited and saved, and the plugin reloaded, it keeps both the old and new quest in memory until a restart, in-case a player is still working on the old quest. This is because it assumes you would like the player to complete what they originally signed up for, rather than be forced into new - and, depending on your changes, potentially impossible - changes.

That said, while it would be possible to ignore the side effects and add a way to force the player to take only the newer quest, the proper solution is to either force the player to quit, or simply restart the server.

**Comment by PikaMug** [comment]
Due to forthcoming changes in the plugin, I've decided to force changes on reload starting with Quests 3.8.0. Although this may lead to some uncomfortable situations, the pros now outweigh the cons with the introduction of deeper Parties integration. Thanks for your patience and understanding in this matter.
