### ISSUE TITLE
Quest gone missing after adding rewards

### ISSUE THREAD

**Issue by Rexcaliburr** [PikaMug/Quests#816]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.0

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
I previously had a quest saved without rewards. I opened up the quest editor again and added in rewards, saved and all, and after reloading the plugin using /questadmin reload, the quest was missing from the editor and quest list though it is still in the quests.yml

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/qQEVRjZ2

**Comment by PikaMug** [comment]
Thanks for the report. Any console errors?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Rexcaliburr** [comment]
Not at all.

**Comment by PikaMug** [comment]
Interesting, because I get the following error:

> [00:07:57 ERROR]: [Quests] name-POTION:amount-1:displayname-Hearty Elixir:meta-type-POTION:custom-color-Color:[rgb0xFFF46B]:custom-effects-[HEAL:0t-x28, ABSORPTION:2147483647t-x8] in items: Reward in Quest Tale of Two Deaths is not properly formatted!
[00:07:57 INFO]: [Quests] Loaded 0 Quest(s), 8 Event(s), 865 Phrase(s)

Which I assume it because of the custom-effects. Will look into supporting this.

**Comment by PikaMug** [comment]
After some further investigation, the current method for reading ItemStack data just isn't going to support custom Potion effects. This is because they use colons as a key/value separator, whereas the underlying file structure uses colons to separate data (and thus they conflict).

The solution for this is also one that's long overdue - to restructure the file structure in a way which will better support colons. This would also negate issues like #808 and better protect the plugin against future Minecraft updates. Problem is, doing this could break current Quests files if not handled carefully.

For now, delete this reward from your config and don't use custom Potion effects. Hopefully I can find the time to improve serialization in the near future.

**Comment by Rexcaliburr** [comment]
Alright, thanks for letting me know! I'll get rid of it and see what else I can throw in instead.

**Comment by PikaMug** [comment]
Resolved with recent dev builds which use an improved method for storing Itemstacks. After updating, you'll have to open the quest in the editor, then save it and run _/questadmin reload_.

https://ci.codemc.org/job/PikaMug/job/Quests/

**Warning:** The builds linked above are experimental. Make sure to back up your Quests folder before attempting to use it.
