### ISSUE TITLE
Erro lang: fil-PH

### ISSUE THREAD

**Issue by CrashyTop** [PikaMug/Quests#850]
**What is your Quests version / build number (do _not_ say "latest")?**
Latest
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?** It is in touch with language, but I did not even touch it, nor did I use it. I'm en-BR.
https://pastebin.com/TxGJzMVQ
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/TxGJzMVQ

**Comment by PikaMug** [comment]
Closing as user did not follow issue instructions (missing version / build number).

I see that you reloaded Quests using [PlugMan](https://dev.bukkit.org/projects/plugman). This is not supported. If the error can be reproduced without reloading, feel free to open a new issue. Otherwise, please use the _/questadmin reload_ command instead of PlugMan.
