### ISSUE TITLE
Quest progress resetting

### ISSUE THREAD

**Issue by ArathiaMC** [PikaMug/Quests#866]
Quests Version: 3.7.6

Quest progress is constantly resetting itself with place block quests. I have a quest that asks players to place different types of blocks such as 30 oak logs, 100 planks and whenever players place for example 25/30 oak logs it then constantly resets back to a lower number such as 8/30. This happens all the time for quests with place block. 

I have a theory that it might just be a visual bug with /quest but I am not entirely sure about that. 

Configuration for said quest:
https://pastebin.com/cZ4Rc4WN

**Comment by ArathiaMC** [comment]
Video: https://drive.google.com/file/d/1qWjH0V6ZukPMQPc1dQJJy2KPgmoafm7v/view

**Comment by PikaMug** [comment]
Possibly related to #793 

@ArathiaMC Could you check whether this behavior appears in the _/quests journal_ as well?

**Comment by ArathiaMC** [comment]
@PikaMug 

Just tested it out and the same happens in Quest Journal.

**Comment by PikaMug** [comment]
Not a duplicate after all.

What's happening is Quests intentionally removes broken blocks from progress to prevent players from placing and breaking the same block repeatedly to complete the quest. The bug is that it's only supposed to do that for blocks of the same type. So, in reference to your video, it's supposed to "reset" like that for logs, but not for the planks.

Using this build will resolve the issue:
https://ci.codemc.org/job/PikaMug/job/Quests/7/
