### ISSUE TITLE
Failed Loading lang files. 

### ISSUE THREAD

**Issue by VirtualPixel** [PikaMug/Quests#873]
**What is your Quests version / build number (do _not_ say "latest")?** 3.7.7-b12

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?** https://pastebin.com/qZYMtm1b

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

I've gone through permissions of the /plugins folder, added everyone and ticked all boxes allowing everything to no avail. 
![image](https://user-images.githubusercontent.com/32817116/61991263-d70bef80-b01b-11e9-8d49-facbd96beff3.png)

After changing permissions, I tried to delete the quests folder within the /plugins folder, it created a new folder and still had the same issue. No change.

**Comment by PikaMug** [comment]
Interesting. Unfortunately, this could be caused by a number of things - your Java environment, a false-positive from antivirus software, or the permissions of parent folders.

Rather than jump down a rabbit hole, just create the /plugins/Quests/lang folder yourself and see if it will generate the files then. If not, download the necessary files from here:
https://github.com/PikaMug/Quests/tree/master/main/src/main/resources/lang
