### ISSUE TITLE
Different color NPC particles

### ISSUE THREAD

**Issue by TheRedMajora** [PikaMug/Quests#875]
**What does your feature do?**
Option for both npc quest particles to be notes, but with different colors.

**How would people use it?**
A new quest could have a yellow note and a redo quest could have a blue note.

**Comment by PikaMug** [comment]
I should note (pun intended) that you can already set the particle type in config.yml under 'npc-effects' but the color cannot be changed. This issue will focus on the color aspect going forward.

**Comment by PikaMug** [comment]
After a bit of research, it seems NOTE particles cannot be colored. Only REDSTONE, SPELL_MOB and SPELL_MOB_AMBIENT can receive color, and only on MC 1.12+.

Since Quests supports versions back to MC 1.7.9, attempting to add this functionality for only 1.12+ is not in line with the project's goals.

Source: https://www.spigotmc.org/wiki/colored-particles/
