### ISSUE TITLE
Option to stop certain messages from being send.

### ISSUE THREAD

**Issue by Technodate** [PikaMug/Quests#881]
**What does your feature do?**
The feature would let players customise the messages send in game even further, in a way where you would be able to fully remove a message from being send, or that the message would only be send to players with certain permission nodes.

At the moment when you're editing the language file, you are not able to leave empty lines, as it will just display as a NULL message in chat. With this feature the NULL message would not be send, and with that the players would be able to not send any messages.

For example;
Whenever a player gets force started/given a quest, it will display in chat for them, but what if I don't want that? Then if players don't have a certain permission node, or if the language file line is empty, they wouldn't be able to see the message in chat.

**How would people use it?**
Here is a language file line from the en-US file;
questForcedTake: "<player> has forced you to take the Quest <quest>."
This will display a message in the chat for the player who has been forced to take a quest.

If the developers or sysadmins decide that they don't want the player to receive a message, they should be able to either leave the line empty or use empty brackets;
questForcedTake: ""
questForcedTake:
questForcedTake: []
questForcedTake: {}

^ 1 of those 4.

This feature would give quests much more customisability, as well as give sysadmins, content makers or anyone else who wants to use the plugin, the option to use quests in their own unique way as they vision it in their eyes.

**Comment by PikaMug** [comment]
Implementing this would be rather cumbersome. Quests' lang strings are modified _after_ the plugin commits to sending a message. In other words, the plugin doesn't check whether or not a string exists prior to sending it to the player. Adding a check for each and every message sent would take far more time than I can spare, especially for the editors (which I'm not sure the Conversation API would support).

It's a nice idea, but not something I can realistically add. My recommendation is to use an empty space so that the message will at least appear blank:

questForcedTake: " "
