### ISSUE TITLE
Delivery message not showing

### ISSUE THREAD

**Issue by KsuKsuKsu** [PikaMug/Quests#911]
Hi again!

Delivery message not showing in game. 
https://pastebin.com/j7smNn5p

http://joxi.ru/5mdRGEZT3dzaPA

Quests 3.7.8

And i found two errors suddenly
1: https://pastebin.com/4Es1mvvV (on click on NPC if you have conversation already)
2: https://pastebin.com/H2hq72b6 (after commands reward on finish quest, for example: https://pastebin.com/sG2YnZ1k)

**Comment by PikaMug** [comment]
Thanks for the report. The command rewards issue is fixed in the 3.8.0 dev builds, available at https://ci.codemc.org/job/PikaMug/job/Quests/

**Warning:** The build linked above is experimental. Make sure to back up your Quests folder before attempting to use it. Alternatively, wait until the final release on Spigot.

**Comment by KsuKsuKsu** [comment]
I will wait. Thank you!
