### ISSUE TITLE
mcmmo premium not found

### ISSUE THREAD

**Issue by Gartentrulla** [PikaMug/Quests#921]
**What is your Quests version / build number (do _not_ say "latest")?**version: 3.7.8-b16
Spigot: 1.14.4
No errors

I installed for mcmmo premium version: 2.1.103
(is not the classic Version) the mcmmoquestmodule.jar in module, but if I want use it for a quest it say, mcmmo not installed. I have this since 1.13.2 and it works the whole time, but since 1.14 it didn't.
Can you help?
Thanks a lot.
With best regards Gartentrulla from Germamy

**Comment by PikaMug** [comment]
Thanks for the report. Once you have installed the module in /plugins/Quests/modules, the new features will be under Custom Rewards/Requirements. The built-in support for mcMMO is for Classic-only.

**Comment by Gartentrulla** [comment]
Hello Dear,
I think you didn’t understand the problem. I have the right version of mcmmo and the module is under module, but ingame, if I want to create a quest it says mcmmo is not istalled, but this is not right. I don’t use the classic version of mcmmo, it is the premium version. If I remove the module the problem is the same, mcmmo will not be found ingame.

Thanks for your help.
With best regards Gartentrulla

**Comment by PikaMug** [comment]
@Gartentrulla Thanks, however I’m confident that I understand the problem. You’re trying to use the built-in options for mcMMO Classic, which show “Not installed”. Even when you install the module for the new mcMMO, it will continue to show “Not installed” because that option is *only* for mcMMO Classic.

The module will give you new options under Custom Rewards and Custom Requirements.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Gartentrulla** [comment]
Hello PikaMug, thanks for the explanation. Now I found the right way, but there is nothing to choose. No parts of skills or any options. Please can you explain what I must do to see which skills I can choose?

I miss an explanation on your side for premium mcmmo.

Thanks a lot.

With best regards from Gartentrulla

**Comment by Gartentrulla** [comment]
Hallo PikaMug,
thanks again, but this is that what I see too. And now? If I write , for expample: alchemie, that’s a german skill, nothing happens. No error. It refresh’s the site and show me the same again.
What must I write or give it the skillnames not in German? 

Sorry, I don’t understand what I have than to do.

Thanks again.

With best regards your Gartentrulla

**Comment by Gartentrulla** [comment]
Dear PikaMug,
many thanks for your help. I will try it tomorrow. But does quests knows, what I want if I write the skill in english, if I use german?
Isn’t it  possible to translate the mcMMO Overhaul Quests Module 1.0 in other languages or to make that it works with other languages?

This were very great. But I try tomorrow and tell you if it works.

With best regards Gartentrulla

**Comment by Gartentrulla** [comment]
Dear PikaMug,
now I tried it again. I have the newest mcmmo premium, no errors, everything is loaded:

[10:08:56] [Server thread/INFO]: [mcMMO] Loading mcMMO v2.1.104
[10:08:56] [Server thread/INFO]: mcMMO has registered WG flags successfully!

[10:08:58] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.1.104
[10:08:59] [Server thread/INFO]: [mcMMO] enabling Acrobatics Skills
[10:08:59] [Server thread/INFO]: [mcMMO] registered subskill: Roll
[10:08:59] [Server thread/INFO]: [mcMMO] 0 entries in mcMMO World Blacklist

[10:09:32] [Server thread/INFO]: [Quests] Loaded 64 Quest(s), 8 Event(s), 862 Phrase(s)
[10:09:32] [Server thread/INFO]: [Quests] Loaded Module: mcMMO Overhaul Skill Requirement by PikaMug
[10:09:32] [Server thread/INFO]: [Quests] Loaded Module: mcMMO Overhaul Skill Reward by PikaMug


but it doesn’t work. Not with the german skillname or the english one.

I get ingame, if I write  a requirement the info, that the plugin overhaul was not found.

I don’t know what I can do.

Thank for your help.

With best regards Gartentrulla

**Comment by PikaMug** [comment]
Thanks. You wrote that “I get ingame... that the plugin overhaul was not found.” Could you share a screenshot of this error?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Gartentrulla** [comment]
Hello PikaMug,
here are the screenshot. Maybe it helps. It shows the way.






Here I set fishing


here the German Angeln and it says: Benutzerdefinierte Voraussetzungs-Modul nicht gefunden



Thanks a lot.

With best regards Gartentrulla

**Comment by PikaMug** [comment]
@Gartentrulla The image is not showing; it seems it wasn't attached to your email.

However, based on the translation you provided, you're seeing the 'reqCustomNotFound` string in-game. This string is displayed from the following code;

https://github.com/PikaMug/Quests/blob/ceb932ec0b3f94e789da41a7c687df1e0d01e031/main/src/main/java/me/blackvein/quests/prompts/RequirementsPrompt.java#L671

It seems what's happening is Quests can't figure out which module you want to use based on what you've typed into chat. Maybe the issue is that you're likely using a German keyboard rather than an English layout. Let's try something:

At the following screen...

![](https://user-images.githubusercontent.com/2267126/63796236-b01f3280-c8d3-11e9-89ab-a5ba1d14fdb8.png)

...copy and paste this text into chat: `mcmmo`

Let me know the results.

**Comment by Gartentrulla** [comment]
Dear PikaMug,
sorry about the pictures, but never mind, your tip was perfect. Thanks so much for your help. Now it works if I write mcmmo. Than I can choose which skill I want.

With a lot of best regards from Gartentrulla
