### ISSUE TITLE
Players cant accept quests until their progress is reset, regardless if new or not.

### ISSUE THREAD

**Issue by lyimpike** [PikaMug/Quests#943]
**What is your Quests version / build number (do _not_ say "latest")?**
3.7.8

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Any new players who join NEED to have their progress reset using /questsadmin reset %p% or they cannot accept any quests. They get error message saying to contact server admin.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://pastebin.com/DG8TzEiQ

**Comment by PikaMug** [comment]
Thanks for your report. Without any error messages or in-game warnings, this is hard to diagnose. My best guess is that your players started a particular Quest, then an administrator modified the quest before they had the chance to complete it. This causes the player to be locked into the original version of the quest in order to prevent them being forced into conditions they did not initially agree to.

Starting with 3.8.0, this behavior will be changed so that edits to the quest will be forcibly applied to players that have already accepted the quest. You could use the latest dev build if you prefer not to wait for the official release. It's available here:

https://ci.codemc.org/job/PikaMug/job/Quests/
