### ISSUE TITLE
Messages Idea

### ISSUE THREAD

**Issue by DeniedINC** [PikaMug/Quests#958]
Allow the messages in the lang file to be enabled or disabled.

Currently when you leave it as "" or '' it leaves a blank line in chat instead of disabling it.

**Comment by PikaMug** [comment]
Thanks for using Quests. Unfortunately, the blank line is what happens when Bukkit/Spigot sends a message of "" to a player. Although it'd certainly be possible to check for a blank message prior to delivery, that would need to be done for each of the 3,498 strings within Quests (as of today, per [Crowdin](https://crowdin.com/project/translate-quests)). Adding that is not something I'm willing to bloat the plugin with all for one feature.

However, if you'd like to provide a _short_ list of messages that you think should behave differently, feel free to name them here and I'll consider making exceptions.

**Comment by DeniedINC** [comment]
Specifically the ones for parties.

questPartiesCreate: "Players added to this party may perform quests together!"
questPartiesDelete: "The quest party was disbanded."
questPartiesInvite: "Player can now perform quests with you!"
questPartiesJoin: "You can now perform quests with player."
questPartiesKicked: "Player can no longer perform quests with you."
questPartiesLeave: "You can no longer perform quests with player."

**Comment by PikaMug** [comment]
@DeniedINC Done. Please give this build a try once available:
https://ci.codemc.io/job/PikaMug/job/Quests/38/

**Comment by DeniedINC** [comment]
Awesome tysm for implementing this so quickly!
