### ISSUE TITLE
Check Inventory for Quest Rewards

### ISSUE THREAD

**Issue by DeniedINC** [PikaMug/Quests#966]
**What does your feature do?**
Instead of having to hold the item and right clicking the NPC, check the inventory of the player for the item and remove it.

**How would people use it?**
As a player it is easier and more intuitive this way

**Comment by PikaMug** [comment]
When delivering an item for an objective, the player must hold the required item to ensure they actually want to hand it over. Often players doing multiple quests will want to deliver for one quest, but not others. Then again, a player may simply want to see what other quests an NPC can offer them, rather than deliver goods. Giving the player control over whether they want to lose the item ensures that mistakes are few and far between.
