### ISSUE TITLE
Clickable text in chat log

### ISSUE THREAD

**Issue by Jakimbo** [PikaMug/Quests#969]
**What does your feature do?**
Like world guard, would allow you to click the options in the chat log instead of typing the option you want to select.
**How would people use it?**
Would allow people to create quests a lot faster than they currently can. I did purchase and try the premium GUI, but after trying both I was able to work a lot faster with world guard's system

**Comment by DeniedINC** [comment]
Honestly while this might be nice I feel like the gui or the text is already super well done.

**Comment by PikaMug** [comment]
Since the last time this was brought up (see #618) I've figured out how to get the Conversation API to accept input without having to enter it in chat (which is how QuestsGUI works). However, I don't recall how I was going to do anything using ClickEvent.Action.RUN_COMMAND. I think the plan was to create a command like _/quests inject 1_ and use the variable to pass information, but I'm not totally sure that'd work. I'll keep this ticket open while I look into it.

**Comment by PikaMug** [comment]
Before I could test my theory, it occurred to me that [Prompt#getPromptText](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/conversations/Prompt.html#getPromptText-org.bukkit.conversations.ConversationContext-) only accepts a String, and since a prompt being open prevents the player from receiving other chat messages, I have no way of sending a message with a ClickEvent. This means that, although my idea for RUN_COMMAND might work, I have no way of making it actionable. Therefore, this idea is dead for now.

I will, however, look into adding an inventory GUI for the Yes/No prompt to QuestsGUI in the future.
