### ISSUE TITLE
Can't use Smoker and Campfire (and possibly blast furnace) for Smelting Quest Requirements.

### ISSUE THREAD

**Issue by Shadorunce** [PikaMug/Quests#976]
**What is your Quests version / build number (do _not_ say "latest")?**
3.8.0-b35

**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
Quest requires to smelt cod and potato specifically, and using a Furnace counts towards the smelting, but using a Smoker and Campfire did not count towards it. If I had to guess, the same would be true for other blocks and the Blast Furnace. The quests were created with 3.7.8 on 1.13.2 if that matters.

**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**
https://hasteb.in/zeludiha.yaml

**Comment by PikaMug** [comment]
This is intentional because Quests tries to remain compatible with older versions of Minecraft which do not have those items. However, it’s not impossible to get this working while maintaining compatibility. I’ll certainly be looking into this in the future, but it’s currently low priority.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Shadorunce** [comment]
I'm not sure exactly how it all works, but what about a check for if the Server version is 1.14+ then also include those other blocks? That way if it's 1.13.x then it'll just skip that check and not even try to recognize that those blocks would even exist. Just a thought.
