### ISSUE TITLE
Objective Scoreboard? (QUEST UI)

### ISSUE THREAD

**Issue by NMLEthereal** [PikaMug/Quests#986]
**What does your feature do?**
Simply puts a Scoreboard on the UI of the screen (already a function in the game i'm sure) to track Quests and Quest Progress
**How would people use it?**
Automatically. It would be a feature to assign certain Quests or all of them just a thing to make the whole thing more immersive.

**Comment by PikaMug** [comment]
Thanks for the suggestion. I've never personally had much interest in adding scoreboard functionality, mainly because Quests is commonly used with mcMMO, which has an affinity for using scoreboards that Quests would have to compete with. However, I wouldn't be opposed to a Pull Request from another developer.

That said, a common workaround is to use [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) (free) in combination with [FeatherBoard](https://www.spigotmc.org/resources/featherboard.2691/) (premium).
